// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'domain/profile.dart';
import 'domain/session.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `forward_json_stream`

Future<SessionInfo> connect({
  required SshProfile profile,
  required int cols,
  required int rows,
}) => RustLib.instance.api.crateApiConnect(
  profile: profile,
  cols: cols,
  rows: rows,
);

Future<void> disconnect({required String sessionId}) =>
    RustLib.instance.api.crateApiDisconnect(sessionId: sessionId);

Future<void> sendTerminalInput({
  required String sessionId,
  required List<int> data,
}) => RustLib.instance.api.crateApiSendTerminalInput(
  sessionId: sessionId,
  data: data,
);

Future<void> resizeTerminal({
  required String sessionId,
  required int cols,
  required int rows,
}) => RustLib.instance.api.crateApiResizeTerminal(
  sessionId: sessionId,
  cols: cols,
  rows: rows,
);

Future<RemoteSystemSnapshot> remoteSystemSnapshot({
  required String sessionId,
}) => RustLib.instance.api.crateApiRemoteSystemSnapshot(sessionId: sessionId);

Future<List<String>> commandHelpSuggestions({
  required String sessionId,
  required String input,
}) => RustLib.instance.api.crateApiCommandHelpSuggestions(
  sessionId: sessionId,
  input: input,
);

Future<String> terminalComplete({required String reqJson}) =>
    RustLib.instance.api.crateApiTerminalComplete(reqJson: reqJson);

Future<List<RemoteFileEntry>> listRemoteDirectory({
  required String sessionId,
  required String path,
}) => RustLib.instance.api.crateApiListRemoteDirectory(
  sessionId: sessionId,
  path: path,
);

Future<String> resolveRemoteDirectory({
  required String sessionId,
  required String path,
}) => RustLib.instance.api.crateApiResolveRemoteDirectory(
  sessionId: sessionId,
  path: path,
);

Future<String> readRemoteFile({
  required String sessionId,
  required String path,
}) => RustLib.instance.api.crateApiReadRemoteFile(
  sessionId: sessionId,
  path: path,
);

Future<Uint8List> readRemoteFileBytes({
  required String sessionId,
  required String path,
}) => RustLib.instance.api.crateApiReadRemoteFileBytes(
  sessionId: sessionId,
  path: path,
);

Future<void> writeRemoteFile({
  required String sessionId,
  required String path,
  required String content,
}) => RustLib.instance.api.crateApiWriteRemoteFile(
  sessionId: sessionId,
  path: path,
  content: content,
);

Future<void> uploadRemoteFile({
  required String sessionId,
  required String path,
  required List<int> data,
}) => RustLib.instance.api.crateApiUploadRemoteFile(
  sessionId: sessionId,
  path: path,
  data: data,
);

Future<void> createRemoteDirectory({
  required String sessionId,
  required String path,
}) => RustLib.instance.api.crateApiCreateRemoteDirectory(
  sessionId: sessionId,
  path: path,
);

Future<void> createRemoteFile({
  required String sessionId,
  required String path,
}) => RustLib.instance.api.crateApiCreateRemoteFile(
  sessionId: sessionId,
  path: path,
);

Future<void> chmodRemotePath({
  required String sessionId,
  required String path,
  required String mode,
}) => RustLib.instance.api.crateApiChmodRemotePath(
  sessionId: sessionId,
  path: path,
  mode: mode,
);

Stream<String> terminalOutputStream() =>
    RustLib.instance.api.crateApiTerminalOutputStream();

Stream<String> connectionStatusStream() =>
    RustLib.instance.api.crateApiConnectionStatusStream();

Stream<String> errorEventStream() =>
    RustLib.instance.api.crateApiErrorEventStream();
