// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'application/rdp_session_manager.dart';
import 'domain/profile.dart';
import 'domain/rdp_profile.dart';
import 'domain/session.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `forward_json_stream`

Future<SessionInfo> connect({
  required SshProfile profile,
  required int cols,
  required int rows,
}) => RustLib.instance.api.crateApiConnect(
  profile: profile,
  cols: cols,
  rows: rows,
);

Future<void> disconnect({required String sessionId}) =>
    RustLib.instance.api.crateApiDisconnect(sessionId: sessionId);

Future<void> sendTerminalInput({
  required String sessionId,
  required List<int> data,
}) => RustLib.instance.api.crateApiSendTerminalInput(
  sessionId: sessionId,
  data: data,
);

Future<void> resizeTerminal({
  required String sessionId,
  required int cols,
  required int rows,
}) => RustLib.instance.api.crateApiResizeTerminal(
  sessionId: sessionId,
  cols: cols,
  rows: rows,
);

Future<RemoteSystemSnapshot> remoteSystemSnapshot({
  required String sessionId,
}) => RustLib.instance.api.crateApiRemoteSystemSnapshot(sessionId: sessionId);

Future<List<String>> commandHelpSuggestions({
  required String sessionId,
  required String input,
}) => RustLib.instance.api.crateApiCommandHelpSuggestions(
  sessionId: sessionId,
  input: input,
);

Future<String> terminalComplete({required String reqJson}) =>
    RustLib.instance.api.crateApiTerminalComplete(reqJson: reqJson);

Future<List<RemoteFileEntry>> listRemoteDirectory({
  required String sessionId,
  required String path,
}) => RustLib.instance.api.crateApiListRemoteDirectory(
  sessionId: sessionId,
  path: path,
);

Future<String> resolveRemoteDirectory({
  required String sessionId,
  required String path,
}) => RustLib.instance.api.crateApiResolveRemoteDirectory(
  sessionId: sessionId,
  path: path,
);

Future<String> readRemoteFile({
  required String sessionId,
  required String path,
}) => RustLib.instance.api.crateApiReadRemoteFile(
  sessionId: sessionId,
  path: path,
);

Future<Uint8List> readRemoteFileBytes({
  required String sessionId,
  required String path,
}) => RustLib.instance.api.crateApiReadRemoteFileBytes(
  sessionId: sessionId,
  path: path,
);

Future<void> writeRemoteFile({
  required String sessionId,
  required String path,
  required String content,
}) => RustLib.instance.api.crateApiWriteRemoteFile(
  sessionId: sessionId,
  path: path,
  content: content,
);

Future<void> uploadRemoteFile({
  required String sessionId,
  required String path,
  required List<int> data,
}) => RustLib.instance.api.crateApiUploadRemoteFile(
  sessionId: sessionId,
  path: path,
  data: data,
);

Future<void> createRemoteDirectory({
  required String sessionId,
  required String path,
}) => RustLib.instance.api.crateApiCreateRemoteDirectory(
  sessionId: sessionId,
  path: path,
);

Future<void> createRemoteFile({
  required String sessionId,
  required String path,
}) => RustLib.instance.api.crateApiCreateRemoteFile(
  sessionId: sessionId,
  path: path,
);

Future<void> chmodRemotePath({
  required String sessionId,
  required String path,
  required String mode,
}) => RustLib.instance.api.crateApiChmodRemotePath(
  sessionId: sessionId,
  path: path,
  mode: mode,
);

Stream<String> terminalOutputStream() =>
    RustLib.instance.api.crateApiTerminalOutputStream();

Stream<String> connectionStatusStream() =>
    RustLib.instance.api.crateApiConnectionStatusStream();

Stream<String> errorEventStream() =>
    RustLib.instance.api.crateApiErrorEventStream();

/// Parse an .rdp file content and return an RdpProfile.
Future<RdpProfile> parseRdpFile({
  required String id,
  required String name,
  required String content,
}) => RustLib.instance.api.crateApiParseRdpFile(
  id: id,
  name: name,
  content: content,
);

/// Connect to an RDP server using the given profile.
Future<RdpSessionInfo> rdpConnect({required RdpProfile profile}) =>
    RustLib.instance.api.crateApiRdpConnect(profile: profile);

/// Disconnect an active RDP session.
Future<void> rdpDisconnect({required String sessionId}) =>
    RustLib.instance.api.crateApiRdpDisconnect(sessionId: sessionId);

/// Send keyboard input to an RDP session.
Future<void> rdpSendKeyboard({
  required String sessionId,
  required int scancode,
  required bool isPressed,
}) => RustLib.instance.api.crateApiRdpSendKeyboard(
  sessionId: sessionId,
  scancode: scancode,
  isPressed: isPressed,
);

/// Send mouse button input to an RDP session.
/// button: 0 = left, 1 = right, 2 = middle
Future<void> rdpSendMouseButton({
  required String sessionId,
  required int x,
  required int y,
  required int button,
  required bool isPressed,
}) => RustLib.instance.api.crateApiRdpSendMouseButton(
  sessionId: sessionId,
  x: x,
  y: y,
  button: button,
  isPressed: isPressed,
);

/// Send mouse move event to an RDP session.
Future<void> rdpSendMouseMove({
  required String sessionId,
  required int x,
  required int y,
}) => RustLib.instance.api.crateApiRdpSendMouseMove(
  sessionId: sessionId,
  x: x,
  y: y,
);

/// Request the current frame buffer as raw RGBA bytes.
Future<Uint8List> rdpRequestFrame({required String sessionId}) =>
    RustLib.instance.api.crateApiRdpRequestFrame(sessionId: sessionId);

/// Stream RDP frame updates (region updates as JSON).
Stream<String> rdpFrameStream() =>
    RustLib.instance.api.crateApiRdpFrameStream();

/// Stream RDP connection status events.
Stream<String> rdpConnectionStatusStream() =>
    RustLib.instance.api.crateApiRdpConnectionStatusStream();

/// Stream RDP error events.
Stream<String> rdpErrorEventStream() =>
    RustLib.instance.api.crateApiRdpErrorEventStream();
