// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'domain/profile.dart';
import 'domain/session.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1290496850;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'portix_serv',
        ioDirectory: '../portix-serv/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiChmodRemotePath({
    required String sessionId,
    required String path,
    required String mode,
  });

  Future<SessionInfo> crateApiConnect({
    required SshProfile profile,
    required int cols,
    required int rows,
  });

  Stream<String> crateApiConnectionStatusStream();

  Future<void> crateApiCreateRemoteDirectory({
    required String sessionId,
    required String path,
  });

  Future<void> crateApiCreateRemoteFile({
    required String sessionId,
    required String path,
  });

  Future<void> crateApiDisconnect({required String sessionId});

  Stream<String> crateApiErrorEventStream();

  Future<void> crateApiInitApp();

  Future<List<RemoteFileEntry>> crateApiListRemoteDirectory({
    required String sessionId,
    required String path,
  });

  Future<String> crateApiReadRemoteFile({
    required String sessionId,
    required String path,
  });

  Future<Uint8List> crateApiReadRemoteFileBytes({
    required String sessionId,
    required String path,
  });

  Future<RemoteSystemSnapshot> crateApiRemoteSystemSnapshot({
    required String sessionId,
  });

  Future<void> crateApiResizeTerminal({
    required String sessionId,
    required int cols,
    required int rows,
  });

  Future<String> crateApiResolveRemoteDirectory({
    required String sessionId,
    required String path,
  });

  Future<void> crateApiSendTerminalInput({
    required String sessionId,
    required List<int> data,
  });

  Stream<String> crateApiTerminalOutputStream();

  Future<void> crateApiUploadRemoteFile({
    required String sessionId,
    required String path,
    required List<int> data,
  });

  Future<void> crateApiWriteRemoteFile({
    required String sessionId,
    required String path,
    required String content,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiChmodRemotePath({
    required String sessionId,
    required String path,
    required String mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(path, serializer);
          sse_encode_String(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiChmodRemotePathConstMeta,
        argValues: [sessionId, path, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChmodRemotePathConstMeta => const TaskConstMeta(
    debugName: "chmod_remote_path",
    argNames: ["sessionId", "path", "mode"],
  );

  @override
  Future<SessionInfo> crateApiConnect({
    required SshProfile profile,
    required int cols,
    required int rows,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_ssh_profile(profile, serializer);
          sse_encode_u_32(cols, serializer);
          sse_encode_u_32(rows, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiConnectConstMeta,
        argValues: [profile, cols, rows],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectConstMeta => const TaskConstMeta(
    debugName: "connect",
    argNames: ["profile", "cols", "rows"],
  );

  @override
  Stream<String> crateApiConnectionStatusStream() {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 3,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiConnectionStatusStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiConnectionStatusStreamConstMeta =>
      const TaskConstMeta(
        debugName: "connection_status_stream",
        argNames: ["sink"],
      );

  @override
  Future<void> crateApiCreateRemoteDirectory({
    required String sessionId,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCreateRemoteDirectoryConstMeta,
        argValues: [sessionId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateRemoteDirectoryConstMeta =>
      const TaskConstMeta(
        debugName: "create_remote_directory",
        argNames: ["sessionId", "path"],
      );

  @override
  Future<void> crateApiCreateRemoteFile({
    required String sessionId,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCreateRemoteFileConstMeta,
        argValues: [sessionId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateRemoteFileConstMeta => const TaskConstMeta(
    debugName: "create_remote_file",
    argNames: ["sessionId", "path"],
  );

  @override
  Future<void> crateApiDisconnect({required String sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDisconnectConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDisconnectConstMeta =>
      const TaskConstMeta(debugName: "disconnect", argNames: ["sessionId"]);

  @override
  Stream<String> crateApiErrorEventStream() {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 7,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiErrorEventStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiErrorEventStreamConstMeta =>
      const TaskConstMeta(debugName: "error_event_stream", argNames: ["sink"]);

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<RemoteFileEntry>> crateApiListRemoteDirectory({
    required String sessionId,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_remote_file_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiListRemoteDirectoryConstMeta,
        argValues: [sessionId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListRemoteDirectoryConstMeta =>
      const TaskConstMeta(
        debugName: "list_remote_directory",
        argNames: ["sessionId", "path"],
      );

  @override
  Future<String> crateApiReadRemoteFile({
    required String sessionId,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiReadRemoteFileConstMeta,
        argValues: [sessionId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReadRemoteFileConstMeta => const TaskConstMeta(
    debugName: "read_remote_file",
    argNames: ["sessionId", "path"],
  );

  @override
  Future<Uint8List> crateApiReadRemoteFileBytes({
    required String sessionId,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiReadRemoteFileBytesConstMeta,
        argValues: [sessionId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReadRemoteFileBytesConstMeta =>
      const TaskConstMeta(
        debugName: "read_remote_file_bytes",
        argNames: ["sessionId", "path"],
      );

  @override
  Future<RemoteSystemSnapshot> crateApiRemoteSystemSnapshot({
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_remote_system_snapshot,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRemoteSystemSnapshotConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRemoteSystemSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "remote_system_snapshot",
        argNames: ["sessionId"],
      );

  @override
  Future<void> crateApiResizeTerminal({
    required String sessionId,
    required int cols,
    required int rows,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_u_32(cols, serializer);
          sse_encode_u_32(rows, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiResizeTerminalConstMeta,
        argValues: [sessionId, cols, rows],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiResizeTerminalConstMeta => const TaskConstMeta(
    debugName: "resize_terminal",
    argNames: ["sessionId", "cols", "rows"],
  );

  @override
  Future<String> crateApiResolveRemoteDirectory({
    required String sessionId,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiResolveRemoteDirectoryConstMeta,
        argValues: [sessionId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiResolveRemoteDirectoryConstMeta =>
      const TaskConstMeta(
        debugName: "resolve_remote_directory",
        argNames: ["sessionId", "path"],
      );

  @override
  Future<void> crateApiSendTerminalInput({
    required String sessionId,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSendTerminalInputConstMeta,
        argValues: [sessionId, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendTerminalInputConstMeta => const TaskConstMeta(
    debugName: "send_terminal_input",
    argNames: ["sessionId", "data"],
  );

  @override
  Stream<String> crateApiTerminalOutputStream() {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 16,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiTerminalOutputStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiTerminalOutputStreamConstMeta =>
      const TaskConstMeta(
        debugName: "terminal_output_stream",
        argNames: ["sink"],
      );

  @override
  Future<void> crateApiUploadRemoteFile({
    required String sessionId,
    required String path,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(path, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiUploadRemoteFileConstMeta,
        argValues: [sessionId, path, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUploadRemoteFileConstMeta => const TaskConstMeta(
    debugName: "upload_remote_file",
    argNames: ["sessionId", "path", "data"],
  );

  @override
  Future<void> crateApiWriteRemoteFile({
    required String sessionId,
    required String path,
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(path, serializer);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWriteRemoteFileConstMeta,
        argValues: [sessionId, path, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWriteRemoteFileConstMeta => const TaskConstMeta(
    debugName: "write_remote_file",
    argNames: ["sessionId", "path", "content"],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  SshProfile dco_decode_box_autoadd_ssh_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ssh_profile(raw);
  }

  @protected
  ConnectionStatus dco_decode_connection_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ConnectionStatus.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RemoteFileEntry> dco_decode_list_remote_file_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_remote_file_entry).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  RemoteFileEntry dco_decode_remote_file_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RemoteFileEntry(
      name: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      isDirectory: dco_decode_bool(arr[2]),
      sizeBytes: dco_decode_u_64(arr[3]),
      modifiedUnixSeconds: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  RemoteSystemSnapshot dco_decode_remote_system_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return RemoteSystemSnapshot(
      os: dco_decode_String(arr[0]),
      hostname: dco_decode_String(arr[1]),
      uptime: dco_decode_String(arr[2]),
      memory: dco_decode_String(arr[3]),
      disk: dco_decode_String(arr[4]),
      memoryUsedBytes: dco_decode_u_64(arr[5]),
      memoryFreeBytes: dco_decode_u_64(arr[6]),
      memoryTotalBytes: dco_decode_u_64(arr[7]),
      diskUsedBytes: dco_decode_u_64(arr[8]),
      diskFreeBytes: dco_decode_u_64(arr[9]),
      diskTotalBytes: dco_decode_u_64(arr[10]),
    );
  }

  @protected
  SessionInfo dco_decode_session_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SessionInfo(
      id: dco_decode_String(arr[0]),
      profileId: dco_decode_String(arr[1]),
      status: dco_decode_connection_status(arr[2]),
    );
  }

  @protected
  SshProfile dco_decode_ssh_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SshProfile(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      host: dco_decode_String(arr[2]),
      port: dco_decode_u_16(arr[3]),
      username: dco_decode_String(arr[4]),
      password: dco_decode_opt_String(arr[5]),
      privateKeyPath: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  SshProfile sse_decode_box_autoadd_ssh_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ssh_profile(deserializer));
  }

  @protected
  ConnectionStatus sse_decode_connection_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ConnectionStatus.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RemoteFileEntry> sse_decode_list_remote_file_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RemoteFileEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_remote_file_entry(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RemoteFileEntry sse_decode_remote_file_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_isDirectory = sse_decode_bool(deserializer);
    var var_sizeBytes = sse_decode_u_64(deserializer);
    var var_modifiedUnixSeconds = sse_decode_i_64(deserializer);
    return RemoteFileEntry(
      name: var_name,
      path: var_path,
      isDirectory: var_isDirectory,
      sizeBytes: var_sizeBytes,
      modifiedUnixSeconds: var_modifiedUnixSeconds,
    );
  }

  @protected
  RemoteSystemSnapshot sse_decode_remote_system_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_os = sse_decode_String(deserializer);
    var var_hostname = sse_decode_String(deserializer);
    var var_uptime = sse_decode_String(deserializer);
    var var_memory = sse_decode_String(deserializer);
    var var_disk = sse_decode_String(deserializer);
    var var_memoryUsedBytes = sse_decode_u_64(deserializer);
    var var_memoryFreeBytes = sse_decode_u_64(deserializer);
    var var_memoryTotalBytes = sse_decode_u_64(deserializer);
    var var_diskUsedBytes = sse_decode_u_64(deserializer);
    var var_diskFreeBytes = sse_decode_u_64(deserializer);
    var var_diskTotalBytes = sse_decode_u_64(deserializer);
    return RemoteSystemSnapshot(
      os: var_os,
      hostname: var_hostname,
      uptime: var_uptime,
      memory: var_memory,
      disk: var_disk,
      memoryUsedBytes: var_memoryUsedBytes,
      memoryFreeBytes: var_memoryFreeBytes,
      memoryTotalBytes: var_memoryTotalBytes,
      diskUsedBytes: var_diskUsedBytes,
      diskFreeBytes: var_diskFreeBytes,
      diskTotalBytes: var_diskTotalBytes,
    );
  }

  @protected
  SessionInfo sse_decode_session_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_profileId = sse_decode_String(deserializer);
    var var_status = sse_decode_connection_status(deserializer);
    return SessionInfo(
      id: var_id,
      profileId: var_profileId,
      status: var_status,
    );
  }

  @protected
  SshProfile sse_decode_ssh_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_password = sse_decode_opt_String(deserializer);
    var var_privateKeyPath = sse_decode_opt_String(deserializer);
    return SshProfile(
      id: var_id,
      name: var_name,
      host: var_host,
      port: var_port,
      username: var_username,
      password: var_password,
      privateKeyPath: var_privateKeyPath,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_ssh_profile(
    SshProfile self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ssh_profile(self, serializer);
  }

  @protected
  void sse_encode_connection_status(
    ConnectionStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_remote_file_entry(
    List<RemoteFileEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_remote_file_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_remote_file_entry(
    RemoteFileEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_bool(self.isDirectory, serializer);
    sse_encode_u_64(self.sizeBytes, serializer);
    sse_encode_i_64(self.modifiedUnixSeconds, serializer);
  }

  @protected
  void sse_encode_remote_system_snapshot(
    RemoteSystemSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.os, serializer);
    sse_encode_String(self.hostname, serializer);
    sse_encode_String(self.uptime, serializer);
    sse_encode_String(self.memory, serializer);
    sse_encode_String(self.disk, serializer);
    sse_encode_u_64(self.memoryUsedBytes, serializer);
    sse_encode_u_64(self.memoryFreeBytes, serializer);
    sse_encode_u_64(self.memoryTotalBytes, serializer);
    sse_encode_u_64(self.diskUsedBytes, serializer);
    sse_encode_u_64(self.diskFreeBytes, serializer);
    sse_encode_u_64(self.diskTotalBytes, serializer);
  }

  @protected
  void sse_encode_session_info(SessionInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.profileId, serializer);
    sse_encode_connection_status(self.status, serializer);
  }

  @protected
  void sse_encode_ssh_profile(SshProfile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_opt_String(self.password, serializer);
    sse_encode_opt_String(self.privateKeyPath, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
