// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'domain/profile.dart';
import 'domain/session.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `forward_json_stream`

/// Parse a .rdp file content string and return session info (not connected yet).
Future<RdpSessionInfo> rdpParseFile({
  required String rdpContent,
  String? profileName,
}) => RdpRustLib.instance.api.crateApiRdpParseFile(
  rdpContent: rdpContent,
  profileName: profileName,
);

/// Connect to an RDP server using the provided profile.
Future<RdpSessionInfo> rdpConnect({required RdpProfile profile}) =>
    RdpRustLib.instance.api.crateApiRdpConnect(profile: profile);

/// Disconnect an active RDP session.
Future<void> rdpDisconnect({required String sessionId}) =>
    RdpRustLib.instance.api.crateApiRdpDisconnect(sessionId: sessionId);

/// Send mouse move event to an active RDP session.
Future<void> rdpSendMouseMove({
  required String sessionId,
  required int x,
  required int y,
}) => RdpRustLib.instance.api.crateApiRdpSendMouseMove(
  sessionId: sessionId,
  x: x,
  y: y,
);

/// Send mouse button event to an active RDP session.
/// button: 1=left, 2=right, 3=middle
Future<void> rdpSendMouseButton({
  required String sessionId,
  required int x,
  required int y,
  required int button,
  required bool down,
}) => RdpRustLib.instance.api.crateApiRdpSendMouseButton(
  sessionId: sessionId,
  x: x,
  y: y,
  button: button,
  down: down,
);

/// Send keyboard input to an active RDP session.
Future<void> rdpSendKeyboardInput({
  required String sessionId,
  required int scancode,
  required bool down,
}) => RdpRustLib.instance.api.crateApiRdpSendKeyboardInput(
  sessionId: sessionId,
  scancode: scancode,
  down: down,
);

/// Stream of bitmap frame updates from all RDP sessions (JSON-serialised RdpFrameEvent).
Stream<String> rdpFrameStream() =>
    RdpRustLib.instance.api.crateApiRdpFrameStream();

/// Stream of connection status updates from all RDP sessions.
Stream<String> rdpStatusStream() =>
    RdpRustLib.instance.api.crateApiRdpStatusStream();

/// Stream of error events from all RDP sessions.
Stream<String> rdpErrorStream() =>
    RdpRustLib.instance.api.crateApiRdpErrorStream();
