// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'domain/events.dart';
import 'domain/profile.dart';
import 'domain/session.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<RdpSessionInfo> rdpParseFile({
  required String rdpContent,
  String? profileName,
}) => RustLib.instance.api.crateApiRdpParseFile(
  rdpContent: rdpContent,
  profileName: profileName,
);

Future<RdpSessionInfo> rdpConnect({required RdpProfile profile}) =>
    RustLib.instance.api.crateApiRdpConnect(profile: profile);

Future<void> rdpDisconnect({required String sessionId}) =>
    RustLib.instance.api.crateApiRdpDisconnect(sessionId: sessionId);

Future<void> rdpSendMouseMove({
  required String sessionId,
  required int x,
  required int y,
}) => RustLib.instance.api.crateApiRdpSendMouseMove(
  sessionId: sessionId,
  x: x,
  y: y,
);

Future<void> rdpSendMouseButton({
  required String sessionId,
  required int x,
  required int y,
  required int button,
  required bool down,
}) => RustLib.instance.api.crateApiRdpSendMouseButton(
  sessionId: sessionId,
  x: x,
  y: y,
  button: button,
  down: down,
);

Future<void> rdpSendMouseWheel({
  required String sessionId,
  required int x,
  required int y,
  required int delta,
  required bool isVertical,
}) => RustLib.instance.api.crateApiRdpSendMouseWheel(
  sessionId: sessionId,
  x: x,
  y: y,
  delta: delta,
  isVertical: isVertical,
);

Future<void> rdpSendKeyboardInput({
  required String sessionId,
  required int scancode,
  required bool down,
}) => RustLib.instance.api.crateApiRdpSendKeyboardInput(
  sessionId: sessionId,
  scancode: scancode,
  down: down,
);

Stream<RdpFrameEvent> rdpFrameStream() =>
    RustLib.instance.api.crateApiRdpFrameStream();

Stream<RdpStatusEvent> rdpStatusStream() =>
    RustLib.instance.api.crateApiRdpStatusStream();

Stream<RdpErrorEvent> rdpErrorStream() =>
    RustLib.instance.api.crateApiRdpErrorStream();
