// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'domain/events.dart';
import 'domain/profile.dart';
import 'domain/session.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<RdpErrorEvent> dco_decode_StreamSink_rdp_error_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<RdpFrameEvent> dco_decode_StreamSink_rdp_frame_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<RdpStatusEvent> dco_decode_StreamSink_rdp_status_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  RdpProfile dco_decode_box_autoadd_rdp_profile(dynamic raw);

  @protected
  int dco_decode_i_16(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  RdpConnectionStatus dco_decode_rdp_connection_status(dynamic raw);

  @protected
  RdpErrorEvent dco_decode_rdp_error_event(dynamic raw);

  @protected
  RdpFrameEvent dco_decode_rdp_frame_event(dynamic raw);

  @protected
  RdpProfile dco_decode_rdp_profile(dynamic raw);

  @protected
  RdpSessionInfo dco_decode_rdp_session_info(dynamic raw);

  @protected
  RdpStatusEvent dco_decode_rdp_status_event(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<RdpErrorEvent> sse_decode_StreamSink_rdp_error_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<RdpFrameEvent> sse_decode_StreamSink_rdp_frame_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<RdpStatusEvent> sse_decode_StreamSink_rdp_status_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  RdpProfile sse_decode_box_autoadd_rdp_profile(SseDeserializer deserializer);

  @protected
  int sse_decode_i_16(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  RdpConnectionStatus sse_decode_rdp_connection_status(
    SseDeserializer deserializer,
  );

  @protected
  RdpErrorEvent sse_decode_rdp_error_event(SseDeserializer deserializer);

  @protected
  RdpFrameEvent sse_decode_rdp_frame_event(SseDeserializer deserializer);

  @protected
  RdpProfile sse_decode_rdp_profile(SseDeserializer deserializer);

  @protected
  RdpSessionInfo sse_decode_rdp_session_info(SseDeserializer deserializer);

  @protected
  RdpStatusEvent sse_decode_rdp_status_event(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_rdp_error_event_Sse(
    RustStreamSink<RdpErrorEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_rdp_frame_event_Sse(
    RustStreamSink<RdpFrameEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_rdp_status_event_Sse(
    RustStreamSink<RdpStatusEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rdp_profile(
    RdpProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_rdp_connection_status(
    RdpConnectionStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rdp_error_event(RdpErrorEvent self, SseSerializer serializer);

  @protected
  void sse_encode_rdp_frame_event(RdpFrameEvent self, SseSerializer serializer);

  @protected
  void sse_encode_rdp_profile(RdpProfile self, SseSerializer serializer);

  @protected
  void sse_encode_rdp_session_info(
    RdpSessionInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rdp_status_event(
    RdpStatusEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
