// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'domain/events.dart';
import 'domain/profile.dart';
import 'domain/session.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RdpRustLib
    extends BaseEntrypoint<RdpRustLibApi, RdpRustLibApiImpl, RdpRustLibWire> {
  @internal
  static final instance = RdpRustLib._();

  RdpRustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RdpRustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RdpRustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RdpRustLibApiImpl, RdpRustLibWire>
  get apiImplConstructor => RdpRustLibApiImpl.new;

  @override
  WireConstructor<RdpRustLibWire> get wireConstructor =>
      RdpRustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitRdpApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 827715397;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'portix_rdp',
        ioDirectory: '../portix_rdp/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RdpRustLibApi extends BaseApi {
  Future<void> crateApiInitRdpApp();

  Future<RdpSessionInfo> crateApiRdpConnect({required RdpProfile profile});

  Future<void> crateApiRdpDisconnect({required String sessionId});

  Stream<RdpErrorEvent> crateApiRdpErrorStream();

  Stream<RdpFrameEvent> crateApiRdpFrameStream();

  Future<RdpSessionInfo> crateApiRdpParseFile({
    required String rdpContent,
    String? profileName,
  });

  Future<void> crateApiRdpSendKeyboardInput({
    required String sessionId,
    required int scancode,
    required bool down,
  });

  Future<void> crateApiRdpSendMouseButton({
    required String sessionId,
    required int x,
    required int y,
    required int button,
    required bool down,
  });

  Future<void> crateApiRdpSendMouseMove({
    required String sessionId,
    required int x,
    required int y,
  });

  Future<void> crateApiRdpSendMouseWheel({
    required String sessionId,
    required int x,
    required int y,
    required int delta,
    required bool isVertical,
  });

  Stream<RdpStatusEvent> crateApiRdpStatusStream();
}

class RdpRustLibApiImpl extends RdpRustLibApiImplPlatform
    implements RdpRustLibApi {
  RdpRustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiInitRdpApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitRdpAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitRdpAppConstMeta =>
      const TaskConstMeta(debugName: "init_rdp_app", argNames: []);

  @override
  Future<RdpSessionInfo> crateApiRdpConnect({required RdpProfile profile}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_rdp_profile(profile, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rdp_session_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRdpConnectConstMeta,
        argValues: [profile],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdpConnectConstMeta =>
      const TaskConstMeta(debugName: "rdp_connect", argNames: ["profile"]);

  @override
  Future<void> crateApiRdpDisconnect({required String sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRdpDisconnectConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdpDisconnectConstMeta =>
      const TaskConstMeta(debugName: "rdp_disconnect", argNames: ["sessionId"]);

  @override
  Stream<RdpErrorEvent> crateApiRdpErrorStream() {
    final sink = RustStreamSink<RdpErrorEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_rdp_error_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 4,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiRdpErrorStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiRdpErrorStreamConstMeta =>
      const TaskConstMeta(debugName: "rdp_error_stream", argNames: ["sink"]);

  @override
  Stream<RdpFrameEvent> crateApiRdpFrameStream() {
    final sink = RustStreamSink<RdpFrameEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_rdp_frame_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 5,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiRdpFrameStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiRdpFrameStreamConstMeta =>
      const TaskConstMeta(debugName: "rdp_frame_stream", argNames: ["sink"]);

  @override
  Future<RdpSessionInfo> crateApiRdpParseFile({
    required String rdpContent,
    String? profileName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(rdpContent, serializer);
          sse_encode_opt_String(profileName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rdp_session_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRdpParseFileConstMeta,
        argValues: [rdpContent, profileName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdpParseFileConstMeta => const TaskConstMeta(
    debugName: "rdp_parse_file",
    argNames: ["rdpContent", "profileName"],
  );

  @override
  Future<void> crateApiRdpSendKeyboardInput({
    required String sessionId,
    required int scancode,
    required bool down,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_u_16(scancode, serializer);
          sse_encode_bool(down, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRdpSendKeyboardInputConstMeta,
        argValues: [sessionId, scancode, down],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdpSendKeyboardInputConstMeta =>
      const TaskConstMeta(
        debugName: "rdp_send_keyboard_input",
        argNames: ["sessionId", "scancode", "down"],
      );

  @override
  Future<void> crateApiRdpSendMouseButton({
    required String sessionId,
    required int x,
    required int y,
    required int button,
    required bool down,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_u_16(x, serializer);
          sse_encode_u_16(y, serializer);
          sse_encode_u_8(button, serializer);
          sse_encode_bool(down, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRdpSendMouseButtonConstMeta,
        argValues: [sessionId, x, y, button, down],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdpSendMouseButtonConstMeta => const TaskConstMeta(
    debugName: "rdp_send_mouse_button",
    argNames: ["sessionId", "x", "y", "button", "down"],
  );

  @override
  Future<void> crateApiRdpSendMouseMove({
    required String sessionId,
    required int x,
    required int y,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_u_16(x, serializer);
          sse_encode_u_16(y, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRdpSendMouseMoveConstMeta,
        argValues: [sessionId, x, y],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdpSendMouseMoveConstMeta => const TaskConstMeta(
    debugName: "rdp_send_mouse_move",
    argNames: ["sessionId", "x", "y"],
  );

  @override
  Future<void> crateApiRdpSendMouseWheel({
    required String sessionId,
    required int x,
    required int y,
    required int delta,
    required bool isVertical,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_u_16(x, serializer);
          sse_encode_u_16(y, serializer);
          sse_encode_i_16(delta, serializer);
          sse_encode_bool(isVertical, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRdpSendMouseWheelConstMeta,
        argValues: [sessionId, x, y, delta, isVertical],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRdpSendMouseWheelConstMeta => const TaskConstMeta(
    debugName: "rdp_send_mouse_wheel",
    argNames: ["sessionId", "x", "y", "delta", "isVertical"],
  );

  @override
  Stream<RdpStatusEvent> crateApiRdpStatusStream() {
    final sink = RustStreamSink<RdpStatusEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_rdp_status_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 11,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiRdpStatusStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiRdpStatusStreamConstMeta =>
      const TaskConstMeta(debugName: "rdp_status_stream", argNames: ["sink"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<RdpErrorEvent> dco_decode_StreamSink_rdp_error_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<RdpFrameEvent> dco_decode_StreamSink_rdp_frame_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<RdpStatusEvent> dco_decode_StreamSink_rdp_status_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  RdpProfile dco_decode_box_autoadd_rdp_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rdp_profile(raw);
  }

  @protected
  int dco_decode_i_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  RdpConnectionStatus dco_decode_rdp_connection_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RdpConnectionStatus.values[raw as int];
  }

  @protected
  RdpErrorEvent dco_decode_rdp_error_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RdpErrorEvent(
      sessionId: dco_decode_opt_String(arr[0]),
      message: dco_decode_String(arr[1]),
      code: dco_decode_String(arr[2]),
    );
  }

  @protected
  RdpFrameEvent dco_decode_rdp_frame_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return RdpFrameEvent(
      sessionId: dco_decode_String(arr[0]),
      data: dco_decode_list_prim_u_8_strict(arr[1]),
      width: dco_decode_u_32(arr[2]),
      height: dco_decode_u_32(arr[3]),
      x: dco_decode_u_32(arr[4]),
      y: dco_decode_u_32(arr[5]),
      frameId: dco_decode_u_64(arr[6]),
    );
  }

  @protected
  RdpProfile dco_decode_rdp_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 17)
      throw Exception('unexpected arr length: expect 17 but see ${arr.length}');
    return RdpProfile(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      host: dco_decode_String(arr[2]),
      port: dco_decode_u_16(arr[3]),
      username: dco_decode_String(arr[4]),
      password: dco_decode_opt_String(arr[5]),
      domain: dco_decode_opt_String(arr[6]),
      desktopWidth: dco_decode_u_16(arr[7]),
      desktopHeight: dco_decode_u_16(arr[8]),
      fullScreen: dco_decode_bool(arr[9]),
      enableCredSsp: dco_decode_bool(arr[10]),
      alternateShell: dco_decode_opt_String(arr[11]),
      sourceRdpContent: dco_decode_opt_String(arr[12]),
      redirectDrives: dco_decode_bool(arr[13]),
      redirectClipboard: dco_decode_bool(arr[14]),
      localSharePath: dco_decode_opt_String(arr[15]),
      localShareName: dco_decode_String(arr[16]),
    );
  }

  @protected
  RdpSessionInfo dco_decode_rdp_session_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RdpSessionInfo(
      id: dco_decode_String(arr[0]),
      profileId: dco_decode_String(arr[1]),
      status: dco_decode_rdp_connection_status(arr[2]),
    );
  }

  @protected
  RdpStatusEvent dco_decode_rdp_status_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RdpStatusEvent(
      sessionId: dco_decode_String(arr[0]),
      status: dco_decode_rdp_connection_status(arr[1]),
      message: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<RdpErrorEvent> sse_decode_StreamSink_rdp_error_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<RdpFrameEvent> sse_decode_StreamSink_rdp_frame_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<RdpStatusEvent> sse_decode_StreamSink_rdp_status_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  RdpProfile sse_decode_box_autoadd_rdp_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rdp_profile(deserializer));
  }

  @protected
  int sse_decode_i_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt16();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RdpConnectionStatus sse_decode_rdp_connection_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RdpConnectionStatus.values[inner];
  }

  @protected
  RdpErrorEvent sse_decode_rdp_error_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_opt_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_code = sse_decode_String(deserializer);
    return RdpErrorEvent(
      sessionId: var_sessionId,
      message: var_message,
      code: var_code,
    );
  }

  @protected
  RdpFrameEvent sse_decode_rdp_frame_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_data = sse_decode_list_prim_u_8_strict(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_x = sse_decode_u_32(deserializer);
    var var_y = sse_decode_u_32(deserializer);
    var var_frameId = sse_decode_u_64(deserializer);
    return RdpFrameEvent(
      sessionId: var_sessionId,
      data: var_data,
      width: var_width,
      height: var_height,
      x: var_x,
      y: var_y,
      frameId: var_frameId,
    );
  }

  @protected
  RdpProfile sse_decode_rdp_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_password = sse_decode_opt_String(deserializer);
    var var_domain = sse_decode_opt_String(deserializer);
    var var_desktopWidth = sse_decode_u_16(deserializer);
    var var_desktopHeight = sse_decode_u_16(deserializer);
    var var_fullScreen = sse_decode_bool(deserializer);
    var var_enableCredSsp = sse_decode_bool(deserializer);
    var var_alternateShell = sse_decode_opt_String(deserializer);
    var var_sourceRdpContent = sse_decode_opt_String(deserializer);
    var var_redirectDrives = sse_decode_bool(deserializer);
    var var_redirectClipboard = sse_decode_bool(deserializer);
    var var_localSharePath = sse_decode_opt_String(deserializer);
    var var_localShareName = sse_decode_String(deserializer);
    return RdpProfile(
      id: var_id,
      name: var_name,
      host: var_host,
      port: var_port,
      username: var_username,
      password: var_password,
      domain: var_domain,
      desktopWidth: var_desktopWidth,
      desktopHeight: var_desktopHeight,
      fullScreen: var_fullScreen,
      enableCredSsp: var_enableCredSsp,
      alternateShell: var_alternateShell,
      sourceRdpContent: var_sourceRdpContent,
      redirectDrives: var_redirectDrives,
      redirectClipboard: var_redirectClipboard,
      localSharePath: var_localSharePath,
      localShareName: var_localShareName,
    );
  }

  @protected
  RdpSessionInfo sse_decode_rdp_session_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_profileId = sse_decode_String(deserializer);
    var var_status = sse_decode_rdp_connection_status(deserializer);
    return RdpSessionInfo(
      id: var_id,
      profileId: var_profileId,
      status: var_status,
    );
  }

  @protected
  RdpStatusEvent sse_decode_rdp_status_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_status = sse_decode_rdp_connection_status(deserializer);
    var var_message = sse_decode_opt_String(deserializer);
    return RdpStatusEvent(
      sessionId: var_sessionId,
      status: var_status,
      message: var_message,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_rdp_error_event_Sse(
    RustStreamSink<RdpErrorEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_rdp_error_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_rdp_frame_event_Sse(
    RustStreamSink<RdpFrameEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_rdp_frame_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_rdp_status_event_Sse(
    RustStreamSink<RdpStatusEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_rdp_status_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_rdp_profile(
    RdpProfile self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rdp_profile(self, serializer);
  }

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt16(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_rdp_connection_status(
    RdpConnectionStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_rdp_error_event(
    RdpErrorEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.sessionId, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_String(self.code, serializer);
  }

  @protected
  void sse_encode_rdp_frame_event(
    RdpFrameEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_list_prim_u_8_strict(self.data, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_u_32(self.x, serializer);
    sse_encode_u_32(self.y, serializer);
    sse_encode_u_64(self.frameId, serializer);
  }

  @protected
  void sse_encode_rdp_profile(RdpProfile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_opt_String(self.password, serializer);
    sse_encode_opt_String(self.domain, serializer);
    sse_encode_u_16(self.desktopWidth, serializer);
    sse_encode_u_16(self.desktopHeight, serializer);
    sse_encode_bool(self.fullScreen, serializer);
    sse_encode_bool(self.enableCredSsp, serializer);
    sse_encode_opt_String(self.alternateShell, serializer);
    sse_encode_opt_String(self.sourceRdpContent, serializer);
    sse_encode_bool(self.redirectDrives, serializer);
    sse_encode_bool(self.redirectClipboard, serializer);
    sse_encode_opt_String(self.localSharePath, serializer);
    sse_encode_String(self.localShareName, serializer);
  }

  @protected
  void sse_encode_rdp_session_info(
    RdpSessionInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.profileId, serializer);
    sse_encode_rdp_connection_status(self.status, serializer);
  }

  @protected
  void sse_encode_rdp_status_event(
    RdpStatusEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_rdp_connection_status(self.status, serializer);
    sse_encode_opt_String(self.message, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
