// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Information about an active RDP session.
class RdpSessionInfo {
  final String id;
  final String profileId;
  final int width;
  final int height;

  const RdpSessionInfo({
    required this.id,
    required this.profileId,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      id.hashCode ^ profileId.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RdpSessionInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          profileId == other.profileId &&
          width == other.width &&
          height == other.height;
}
