// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/profile.dart';
import '../domain/sftp.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Opens an SFTP connection and returns its id.
Future<String> sftpConnect({required SshProfile profile}) =>
    RustLib.instance.api.crateApiSftpSftpConnect(profile: profile);

Future<void> sftpDisconnect({required String sessionId}) =>
    RustLib.instance.api.crateApiSftpSftpDisconnect(sessionId: sessionId);

/// False once the connection dropped (it is then forgotten).
Future<bool> sftpIsAlive({required String sessionId}) =>
    RustLib.instance.api.crateApiSftpSftpIsAlive(sessionId: sessionId);

/// Absolute path for [path]; `~` and `~/…` are relative to the login folder.
Future<String> sftpResolve({required String sessionId, required String path}) =>
    RustLib.instance.api.crateApiSftpSftpResolve(
      sessionId: sessionId,
      path: path,
    );

Future<List<RemoteFileEntry>> sftpList({
  required String sessionId,
  required String path,
}) =>
    RustLib.instance.api.crateApiSftpSftpList(sessionId: sessionId, path: path);

Future<Uint8List> sftpRead({required String sessionId, required String path}) =>
    RustLib.instance.api.crateApiSftpSftpRead(sessionId: sessionId, path: path);

/// Overwrites [path] in place (keeps its permissions); creates it if missing.
Future<void> sftpWrite({
  required String sessionId,
  required String path,
  required List<int> data,
}) => RustLib.instance.api.crateApiSftpSftpWrite(
  sessionId: sessionId,
  path: path,
  data: data,
);

Future<void> sftpCreateDir({required String sessionId, required String path}) =>
    RustLib.instance.api.crateApiSftpSftpCreateDir(
      sessionId: sessionId,
      path: path,
    );

Future<void> sftpCreateFile({
  required String sessionId,
  required String path,
}) => RustLib.instance.api.crateApiSftpSftpCreateFile(
  sessionId: sessionId,
  path: path,
);

/// [mode] is the permission bits, e.g. 0o755.
Future<void> sftpChmod({
  required String sessionId,
  required String path,
  required int mode,
}) => RustLib.instance.api.crateApiSftpSftpChmod(
  sessionId: sessionId,
  path: path,
  mode: mode,
);

Future<void> sftpRename({
  required String sessionId,
  required String from,
  required String to,
}) => RustLib.instance.api.crateApiSftpSftpRename(
  sessionId: sessionId,
  from: from,
  to: to,
);

/// Deletes a file or a whole folder.
Future<void> sftpRemove({required String sessionId, required String path}) =>
    RustLib.instance.api.crateApiSftpSftpRemove(
      sessionId: sessionId,
      path: path,
    );

/// Copies a file or folder on the server.
Future<void> sftpCopy({
  required String sessionId,
  required String from,
  required String to,
}) => RustLib.instance.api.crateApiSftpSftpCopy(
  sessionId: sessionId,
  from: from,
  to: to,
);

/// Downloads [remote_path] to [local_path], reporting progress on the
/// returned stream, which ends when done or carries the error. An earlier
/// interrupted download of the same file resumes. Cancelling the stream
/// subscription stops the transfer (the partial file is kept for resuming).
Stream<TransferProgress> sftpDownload({
  required String sessionId,
  required String remotePath,
  required String localPath,
}) => RustLib.instance.api.crateApiSftpSftpDownload(
  sessionId: sessionId,
  remotePath: remotePath,
  localPath: localPath,
);

/// Uploads [local_path] to [remote_path]; same stream, resume and cancel
/// behaviour as [sftp_download]. A replaced file keeps its permissions.
Stream<TransferProgress> sftpUpload({
  required String sessionId,
  required String localPath,
  required String remotePath,
}) => RustLib.instance.api.crateApiSftpSftpUpload(
  sessionId: sessionId,
  localPath: localPath,
  remotePath: remotePath,
);
