// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/profile.dart';
import '../domain/session.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `forward_json_stream`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

Future<SessionInfo> connect({
  required SshProfile profile,
  required int cols,
  required int rows,
}) => RustLib.instance.api.crateApiSshConnect(
  profile: profile,
  cols: cols,
  rows: rows,
);

Future<void> disconnect({required String sessionId}) =>
    RustLib.instance.api.crateApiSshDisconnect(sessionId: sessionId);

Future<void> sendTerminalInput({
  required String sessionId,
  required List<int> data,
}) => RustLib.instance.api.crateApiSshSendTerminalInput(
  sessionId: sessionId,
  data: data,
);

Future<void> resizeTerminal({
  required String sessionId,
  required int cols,
  required int rows,
}) => RustLib.instance.api.crateApiSshResizeTerminal(
  sessionId: sessionId,
  cols: cols,
  rows: rows,
);

Future<RemoteSystemSnapshot> remoteSystemSnapshot({
  required String sessionId,
}) =>
    RustLib.instance.api.crateApiSshRemoteSystemSnapshot(sessionId: sessionId);

Future<List<String>> commandHelpSuggestions({
  required String sessionId,
  required String input,
}) => RustLib.instance.api.crateApiSshCommandHelpSuggestions(
  sessionId: sessionId,
  input: input,
);

Future<String> terminalComplete({required String reqJson}) =>
    RustLib.instance.api.crateApiSshTerminalComplete(reqJson: reqJson);

/// Generates an unencrypted ed25519 keypair: the private key at `path` (0600
/// on unix) and the public key at `path.pub`. Refuses to overwrite either
/// file. Returns the OpenSSH public key line (for `authorized_keys`).
///
/// A non-empty `passphrase` encrypts the private key (the connect path asks
/// for it when needed).
Future<String> generateEd25519Key({
  required String path,
  required String comment,
  String? passphrase,
}) => RustLib.instance.api.crateApiSshGenerateEd25519Key(
  path: path,
  comment: comment,
  passphrase: passphrase,
);

/// The host key refused during the last connect to `host:port`, so the UI can
/// ask the user to confirm it (unknown host) or explain the risk (changed key).
Future<HostKeyInfo?> pendingHostKey({
  required String host,
  required int port,
}) => RustLib.instance.api.crateApiSshPendingHostKey(host: host, port: port);

/// Records the refused key of an unknown host in ~/.ssh/known_hosts after the
/// user confirmed `fingerprint`. Fails for a changed key or a stale fingerprint.
Future<void> trustHostKey({
  required String host,
  required int port,
  required String fingerprint,
}) => RustLib.instance.api.crateApiSshTrustHostKey(
  host: host,
  port: port,
  fingerprint: fingerprint,
);

/// Starts forwarding 127.0.0.1:`local_port` (0 = any free port) to
/// `remote_host:remote_port` as seen from the SSH server, over a dedicated
/// connection. Returns once listening and connected.
Future<ForwardInfo> startLocalForward({
  required SshProfile profile,
  required int localPort,
  required String remoteHost,
  required int remotePort,
}) => RustLib.instance.api.crateApiSshStartLocalForward(
  profile: profile,
  localPort: localPort,
  remoteHost: remoteHost,
  remotePort: remotePort,
);

Future<void> stopLocalForward({required String id}) =>
    RustLib.instance.api.crateApiSshStopLocalForward(id: id);

/// Tunnels still running (one ends on its own when its SSH connection drops).
Future<List<ForwardInfo>> listLocalForwards() =>
    RustLib.instance.api.crateApiSshListLocalForwards();

Stream<String> terminalOutputStream() =>
    RustLib.instance.api.crateApiSshTerminalOutputStream();

Stream<String> connectionStatusStream() =>
    RustLib.instance.api.crateApiSshConnectionStatusStream();

Stream<String> errorEventStream() =>
    RustLib.instance.api.crateApiSshErrorEventStream();

/// An active local port forward (`ssh -L local_port:remote_host:remote_port`).
class ForwardInfo {
  final String id;
  final String profileId;
  final int localPort;
  final String remoteHost;
  final int remotePort;

  const ForwardInfo({
    required this.id,
    required this.profileId,
    required this.localPort,
    required this.remoteHost,
    required this.remotePort,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      profileId.hashCode ^
      localPort.hashCode ^
      remoteHost.hashCode ^
      remotePort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ForwardInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          profileId == other.profileId &&
          localPort == other.localPort &&
          remoteHost == other.remoteHost &&
          remotePort == other.remotePort;
}

/// A server host key that was refused: unknown (`changed_line` is None) or
/// different from the key recorded on `changed_line` of known_hosts.
class HostKeyInfo {
  final String algorithm;
  final String fingerprint;
  final int? changedLine;

  const HostKeyInfo({
    required this.algorithm,
    required this.fingerprint,
    this.changedLine,
  });

  @override
  int get hashCode =>
      algorithm.hashCode ^ fingerprint.hashCode ^ changedLine.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostKeyInfo &&
          runtimeType == other.runtimeType &&
          algorithm == other.algorithm &&
          fingerprint == other.fingerprint &&
          changedLine == other.changedLine;
}
