part of '../terminal_workspace_view.dart';

const portixTerminalTheme = TerminalTheme(
  cursor: AppColors.green,
  selection: Color(0x663A78B7),
  foreground: AppColors.text,
  background: AppColors.terminal,
  black: Color(0xFF020814),
  red: AppColors.danger,
  green: AppColors.green,
  yellow: AppColors.amber,
  blue: AppColors.primaryBlue,
  magenta: Color(0xFFFF6BD6),
  cyan: AppColors.cyan,
  white: AppColors.text,
  brightBlack: AppColors.muted,
  brightRed: Color(0xFFFF7C9B),
  brightGreen: Color(0xFF49F5A5),
  brightYellow: Color(0xFFFFD37A),
  brightBlue: Color(0xFF69A3FF),
  brightMagenta: Color(0xFFFF95E2),
  brightCyan: Color(0xFF71E9FF),
  brightWhite: Colors.white,
  searchHitBackground: Color(0x66406200),
  searchHitBackgroundCurrent: Color(0xAA805800),
  searchHitForeground: AppColors.text,
);
