// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Represents an RDP connection profile, either created manually or parsed from a .rdp file.
class RdpProfile {
  final String id;
  final String name;
  final String host;
  final int port;
  final String username;
  final String? password;
  final String? domain;
  final int width;
  final int height;

  /// Screen mode: 1 = windowed, 2 = fullscreen
  final int screenMode;

  /// Additional RDP settings parsed from file
  final Map<String, String> extra;

  const RdpProfile({
    required this.id,
    required this.name,
    required this.host,
    required this.port,
    required this.username,
    this.password,
    this.domain,
    required this.width,
    required this.height,
    required this.screenMode,
    required this.extra,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      password.hashCode ^
      domain.hashCode ^
      width.hashCode ^
      height.hashCode ^
      screenMode.hashCode ^
      extra.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RdpProfile &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          password == other.password &&
          domain == other.domain &&
          width == other.width &&
          height == other.height &&
          screenMode == other.screenMode &&
          extra == other.extra;
}
