// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'session.dart';

class RdpErrorEvent {
  final String? sessionId;
  final String message;
  final String code;

  const RdpErrorEvent({
    this.sessionId,
    required this.message,
    required this.code,
  });

  @override
  int get hashCode => sessionId.hashCode ^ message.hashCode ^ code.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RdpErrorEvent &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          message == other.message &&
          code == other.code;
}

class RdpFrameEvent {
  final String sessionId;
  final Uint8List data;
  final int width;
  final int height;
  final int x;
  final int y;
  final BigInt frameId;
  final int chunkIndex;
  final int chunkCount;

  const RdpFrameEvent({
    required this.sessionId,
    required this.data,
    required this.width,
    required this.height,
    required this.x,
    required this.y,
    required this.frameId,
    required this.chunkIndex,
    required this.chunkCount,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      data.hashCode ^
      width.hashCode ^
      height.hashCode ^
      x.hashCode ^
      y.hashCode ^
      frameId.hashCode ^
      chunkIndex.hashCode ^
      chunkCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RdpFrameEvent &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          data == other.data &&
          width == other.width &&
          height == other.height &&
          x == other.x &&
          y == other.y &&
          frameId == other.frameId &&
          chunkIndex == other.chunkIndex &&
          chunkCount == other.chunkCount;
}

class RdpStatusEvent {
  final String sessionId;
  final RdpConnectionStatus status;
  final String? message;

  const RdpStatusEvent({
    required this.sessionId,
    required this.status,
    this.message,
  });

  @override
  int get hashCode => sessionId.hashCode ^ status.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RdpStatusEvent &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          status == other.status &&
          message == other.message;
}
