// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class RdpProfile {
  final String id;
  final String name;
  final String host;
  final int port;
  final String username;
  final String? password;
  final String? domain;
  final int desktopWidth;
  final int desktopHeight;
  final bool fullScreen;
  final bool enableCredSsp;

  /// Alternate shell (used by CyberArk PSM)
  final String? alternateShell;

  /// Original .rdp file content (for CyberArk PSM pass-through)
  final String? sourceRdpContent;

  const RdpProfile({
    required this.id,
    required this.name,
    required this.host,
    required this.port,
    required this.username,
    this.password,
    this.domain,
    required this.desktopWidth,
    required this.desktopHeight,
    required this.fullScreen,
    required this.enableCredSsp,
    this.alternateShell,
    this.sourceRdpContent,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      password.hashCode ^
      domain.hashCode ^
      desktopWidth.hashCode ^
      desktopHeight.hashCode ^
      fullScreen.hashCode ^
      enableCredSsp.hashCode ^
      alternateShell.hashCode ^
      sourceRdpContent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RdpProfile &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          password == other.password &&
          domain == other.domain &&
          desktopWidth == other.desktopWidth &&
          desktopHeight == other.desktopHeight &&
          fullScreen == other.fullScreen &&
          enableCredSsp == other.enableCredSsp &&
          alternateShell == other.alternateShell &&
          sourceRdpContent == other.sourceRdpContent;
}
