// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

enum RdpConnectionStatus { disconnected, connecting, connected, error }

class RdpSessionInfo {
  final String id;
  final String profileId;
  final RdpConnectionStatus status;

  const RdpSessionInfo({
    required this.id,
    required this.profileId,
    required this.status,
  });

  @override
  int get hashCode => id.hashCode ^ profileId.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RdpSessionInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          profileId == other.profileId &&
          status == other.status;
}
