use crate::domain::autocomplete::{CompletionItem, CompletionKind};

pub struct OptionProvider;

impl OptionProvider {
    pub fn complete(command: &str, token: &str, limit: usize) -> Vec<CompletionItem> {
        let options = known_options(command);
        if options.is_empty() {
            return Vec::new();
        }

        options
            .iter()
            .filter(|(flag, _)| flag.starts_with(token))
            .take(limit)
            .map(|(flag, desc)| CompletionItem {
                label: format!("{flag}  {desc}"),
                insert_text: flag.to_string(),
                kind: CompletionKind::Command,
                description: Some(desc.to_string()),
                score: 90,
            })
            .collect()
    }

    /// Returns an inline suggestion suffix for partial flag input.
    /// E.g., input "-lr" with known option "-lrth" returns Some("th").
    pub fn inline_suggestion(command: &str, token: &str) -> Option<String> {
        if token.len() < 2 || token.starts_with("--") {
            return None;
        }
        let options = known_options(command);
        // Find the best matching combined flag option.
        for (flag, _) in options {
            if flag.len() > token.len() && flag.starts_with(token) {
                let suffix = &flag[token.len()..];
                return Some(suffix.to_owned());
            }
        }
        None
    }
}

fn known_options(command: &str) -> &'static [(&'static str, &'static str)] {
    match command {
        "ls" => &[
            ("-l", "long listing format"),
            ("-a", "show hidden files"),
            ("-h", "human-readable sizes"),
            ("-R", "list recursively"),
            ("-t", "sort by modification time"),
            ("-r", "reverse sort order"),
            ("-S", "sort by file size"),
            ("-1", "one file per line"),
            ("-d", "list directories themselves"),
            ("-i", "show inode numbers"),
            ("-n", "numeric uid/gid"),
            ("-lrth", "long + reverse + time + human (common)"),
            ("-la", "long listing with hidden files"),
            ("-lah", "long + all + human-readable"),
            ("-lhS", "sort by size, largest first"),
            ("-li", "show inodes for hard link debug"),
            ("--color=auto", "colorize output"),
            ("--all", "show hidden files"),
            ("--human-readable", "human-readable sizes"),
            ("--recursive", "list recursively"),
        ],
        "grep" => &[
            ("-r", "recursive search"),
            ("-R", "recursive, follow symlinks"),
            ("-i", "ignore case"),
            ("-n", "show line numbers"),
            ("-l", "files with matches only"),
            ("-v", "invert match"),
            ("-c", "count matches"),
            ("-w", "match whole words"),
            ("-E", "extended regex"),
            ("-P", "perl regex"),
            ("-A", "lines after match"),
            ("-B", "lines before match"),
            ("-C", "context lines around match"),
            ("-Rni", "recursive + line numbers + ignore case"),
            ("--include=", "search only matching files"),
            ("--exclude=", "skip matching files"),
            ("--exclude-dir=", "skip directories (e.g. .git)"),
            ("--color=auto", "highlight matches"),
        ],
        "rg" => &[
            ("-n", "show line numbers"),
            ("-i", "ignore case"),
            ("-l", "only list matching filenames"),
            ("-g", "glob filter (e.g. '*.rs')"),
            ("-C", "context lines around match"),
            ("--hidden", "search hidden files"),
            ("--glob", "include/exclude glob pattern"),
            ("--files", "list files that would be searched"),
            ("--json", "output machine-readable JSON"),
        ],
        "find" => &[
            ("-name", "match filename pattern"),
            ("-iname", "case-insensitive name"),
            ("-type", "file type (f=file, d=dir)"),
            ("-size", "file size (+100M, -1k)"),
            ("-mtime", "modification time in days"),
            ("-exec", "execute command on results"),
            ("-delete", "delete matching files"),
            ("-maxdepth", "max directory depth"),
            ("-mindepth", "min directory depth"),
            ("-perm", "file permissions"),
            ("-user", "file owner"),
            ("-group", "file group"),
            ("-empty", "find empty files/dirs"),
            ("-prune", "skip directory tree"),
            ("-print0", "null-separated output for xargs"),
        ],
        "chmod" => &[
            ("+x", "make executable"),
            ("-R", "recursive"),
            ("-v", "verbose"),
            ("644", "owner rw, group/other r"),
            ("755", "owner rwx, group/other rx"),
            ("600", "owner rw only (e.g. SSH keys)"),
            ("--recursive", "change recursively"),
        ],
        "chown" => &[
            ("-R", "recursive"),
            ("-v", "verbose"),
            ("--recursive", "change recursively"),
        ],
        "cp" => &[
            ("-r", "copy directories recursively"),
            ("-v", "verbose"),
            ("-i", "prompt before overwrite"),
            ("-f", "force overwrite"),
            ("-p", "preserve attributes"),
            ("-a", "archive mode (-dR --preserve=all)"),
            ("--backup", "make backup of each file"),
        ],
        "mv" => &[
            ("-v", "verbose"),
            ("-i", "prompt before overwrite"),
            ("-f", "force overwrite"),
            ("-n", "no overwrite"),
            ("--backup", "make backup of each file"),
        ],
        "rm" => &[
            ("-r", "remove directories recursively"),
            ("-f", "force remove"),
            ("-v", "verbose"),
            ("-i", "prompt before removal"),
            ("-rf", "force recursive remove (careful!)"),
            ("--no-preserve-root", "allow removing /"),
        ],
        "mkdir" => &[
            ("-p", "create parent directories"),
            ("-v", "verbose"),
            ("-m", "set permissions mode"),
        ],
        "cat" => &[
            ("-n", "number all lines"),
            ("-b", "number non-blank lines"),
            ("-s", "squeeze blank lines"),
            ("-A", "show all (tabs, endings)"),
        ],
        "tail" => &[
            ("-f", "follow file growth"),
            ("-F", "follow with retry (across rotation)"),
            ("-n", "number of lines"),
            ("--pid=", "terminate after pid dies"),
        ],
        "head" => &[
            ("-n", "number of lines"),
            ("-c", "number of bytes (e.g. 1M)"),
        ],
        "less" => &[
            ("+F", "follow mode (like tail -f)"),
            ("-N", "show line numbers"),
            ("-S", "chop long lines"),
        ],
        "tar" => &[
            ("-c", "create archive"),
            ("-x", "extract archive"),
            ("-z", "gzip compression"),
            ("-j", "bzip2 compression"),
            ("-v", "verbose"),
            ("-f", "archive file name"),
            ("-t", "list archive contents"),
            ("-C", "change directory"),
            ("-czvf", "create gzip tar (common)"),
            ("-xzvf", "extract gzip tar (common)"),
            ("-tzvf", "list gzip tar contents"),
            ("--exclude=", "exclude pattern"),
        ],
        "zip" => &[
            ("-r", "recursive (directories)"),
            ("-e", "encrypt with password"),
            ("-9", "max compression"),
        ],
        "gzip" => &[
            ("-k", "keep original file"),
            ("-d", "decompress"),
            ("-9", "max compression"),
        ],
        "curl" => &[
            ("-o", "output to file"),
            ("-O", "save with remote filename"),
            ("-s", "silent mode"),
            ("-S", "show error with silent"),
            ("-L", "follow redirects"),
            ("-v", "verbose"),
            ("-X", "request method (GET, POST...)"),
            ("-H", "add header"),
            ("-d", "POST data"),
            ("-k", "allow insecure SSL"),
            ("-I", "headers only"),
            ("-w", "write-out format (e.g. %{http_code})"),
            ("--max-time", "timeout in seconds"),
            ("--retry", "retry count"),
            ("--retry-delay", "delay between retries"),
            ("-sS", "silent but show errors"),
        ],
        "wget" => &[
            ("-O", "output file"),
            ("-q", "quiet"),
            ("-c", "continue partial download"),
            ("-r", "recursive download"),
            ("--no-check-certificate", "skip SSL verify"),
        ],
        "docker" => &[
            ("ps", "list running containers"),
            ("ps -a", "list all containers"),
            ("images", "list images"),
            ("run", "run a container"),
            ("exec", "exec into container"),
            ("logs", "view container logs"),
            ("logs -f", "follow container logs"),
            ("build", "build image"),
            ("pull", "pull image"),
            ("push", "push image"),
            ("stop", "stop container"),
            ("rm", "remove container"),
            ("rmi", "remove image"),
            ("inspect", "show container metadata"),
            ("system prune -af", "clean unused objects (careful!)"),
            ("compose", "docker compose"),
        ],
        "docker compose" => &[
            ("up", "start services"),
            ("up -d", "start in background"),
            ("down", "stop and remove services"),
            ("logs -f", "follow all logs"),
            ("exec", "shell into service container"),
            ("ps", "list compose containers"),
            ("build --no-cache", "rebuild without cache"),
            ("pull", "pull latest images"),
            ("restart", "restart a service"),
        ],
        "kubectl" => &[
            ("get pods", "list pods"),
            ("get pods -A", "list pods all namespaces"),
            ("get svc", "list services"),
            ("get deploy", "list deployments"),
            ("describe pod", "inspect pod details"),
            ("logs -f", "follow pod logs"),
            ("exec -it", "shell into pod"),
            ("apply -f", "apply manifest"),
            ("rollout status", "watch deployment rollout"),
            ("rollout restart", "restart deployment pods"),
            ("-n", "namespace"),
            ("-o json", "output as JSON"),
            ("-o wide", "wide output"),
        ],
        "git" => &[
            ("status", "show working tree status"),
            ("status -sb", "short branch status"),
            ("log --oneline", "compact history"),
            ("log --graph", "visual branch history"),
            ("diff", "show unstaged changes"),
            ("diff --staged", "show staged changes"),
            ("add -p", "interactively stage hunks"),
            ("commit -m", "commit with message"),
            ("pull --rebase", "pull + rebase local"),
            ("fetch --prune", "fetch + clean deleted remote"),
            ("checkout -b", "create and switch branch"),
            ("stash push -m", "save temporary work"),
            ("branch -d", "delete merged branch"),
            ("rebase", "rebase branch"),
            ("merge", "merge branch"),
            ("cherry-pick", "apply specific commit"),
            ("reset --soft", "undo commit, keep changes"),
            ("reset --hard", "undo commit, discard changes"),
        ],
        "systemctl" => &[
            ("start", "start a service"),
            ("stop", "stop a service"),
            ("restart", "restart a service"),
            ("status", "show service status"),
            ("enable", "enable service at boot"),
            ("disable", "disable service at boot"),
            ("reload", "reload service config"),
            ("daemon-reload", "reload systemd config"),
            ("list-units", "list loaded units"),
            ("list-unit-files", "list installed units"),
        ],
        "journalctl" => &[
            ("-u", "show unit logs"),
            ("-f", "follow logs"),
            ("-n", "number of lines"),
            ("--since", "filter by time (e.g. '1 hour ago')"),
            ("-p err", "show only errors"),
            ("-b", "current boot only"),
            ("--no-pager", "disable paging"),
        ],
        "ssh" => &[
            ("-p", "port number"),
            ("-i", "identity file (private key)"),
            ("-v", "verbose mode"),
            ("-N", "no remote command (tunnel only)"),
            ("-L", "local port forwarding"),
            ("-R", "remote port forwarding"),
            ("-D", "dynamic SOCKS forwarding"),
            ("-o", "option (e.g. StrictHostKeyChecking=no)"),
            ("-q", "quiet mode"),
        ],
        "scp" => &[
            ("-r", "recursive copy"),
            ("-P", "port number"),
            ("-i", "identity file"),
            ("-v", "verbose"),
            ("-C", "compression"),
        ],
        "rsync" => &[
            ("-a", "archive mode"),
            ("-v", "verbose"),
            ("-z", "compress during transfer"),
            ("-P", "show progress + partial"),
            ("-n", "dry run"),
            ("-avz", "archive + verbose + compress (common)"),
            ("-avzn", "dry-run sync before applying"),
            ("--delete", "delete extraneous files"),
            ("--exclude=", "exclude pattern"),
            ("-e", "specify remote shell"),
        ],
        "ps" => &[
            ("aux", "all processes (BSD style)"),
            ("-ef", "all processes (POSIX)"),
            ("-p", "select by PID"),
            ("-u", "select by user"),
            ("-eo", "custom output format"),
            ("--sort=-%cpu", "sort by CPU desc"),
            ("--forest", "show process tree"),
        ],
        "kill" => &[
            ("-9", "SIGKILL (force kill)"),
            ("-15", "SIGTERM (graceful)"),
            ("-l", "list signal names"),
            ("-s", "specify signal"),
        ],
        "pgrep" => &[
            ("-a", "show full command"),
            ("-f", "match against full command"),
            ("-l", "list PID and name"),
        ],
        "pkill" => &[
            ("-f", "match full command string"),
            ("-9", "force kill matching"),
        ],
        "du" => &[
            ("-h", "human-readable sizes"),
            ("-s", "summary total only"),
            ("-sh", "summary human-readable (common)"),
            ("-ah", "all files human-readable"),
            ("-d", "max depth"),
            ("--max-depth=", "max directory depth"),
        ],
        "df" => &[
            ("-h", "human-readable sizes"),
            ("-T", "show filesystem type"),
            ("-Th", "type + human-readable"),
            ("-i", "show inode info"),
            ("-ih", "inode + human-readable"),
        ],
        "awk" => &[
            ("-F", "field separator (e.g. -F: -F,)"),
            ("'{print $1}'", "print first column"),
            ("'NR>1'", "skip header line"),
            ("'!seen[$0]++'", "remove duplicate lines"),
        ],
        "sed" => &[
            ("-n", "suppress default output"),
            ("-i", "edit file in place"),
            ("-i.bak", "in-place with backup"),
            ("'s/old/new/g'", "replace all occurrences"),
            ("'/^#/d'", "remove comment lines"),
            ("'/^$/d'", "remove blank lines"),
        ],
        "jq" => &[
            (".", "pretty-print JSON"),
            ("-r", "raw string output"),
            ("-s", "slurp (read all into array)"),
            ("--arg", "inject shell variable"),
            ("'keys'", "list JSON object keys"),
            ("'map(select(...))'", "filter array"),
        ],
        "xargs" => &[
            ("-r", "don't run if empty"),
            ("-n1", "one argument per command"),
            ("-0", "null-separated input"),
            ("-I{}", "replace string placeholder"),
            ("-P", "parallel processes"),
        ],
        "sort" => &[
            ("-n", "numeric sort"),
            ("-r", "reverse order"),
            ("-u", "unique (remove dups)"),
            ("-k", "sort by field"),
            ("-t", "field delimiter"),
            ("-h", "human-numeric sort (1K, 2M)"),
            ("-nr", "numeric reverse (common)"),
            ("-rh", "reverse human-numeric"),
        ],
        "uniq" => &[
            ("-c", "count occurrences"),
            ("-d", "only show duplicates"),
            ("-u", "only show unique lines"),
        ],
        "wc" => &[
            ("-l", "count lines"),
            ("-w", "count words"),
            ("-c", "count bytes"),
            ("-m", "count characters"),
        ],
        "cut" => &[
            ("-d", "delimiter (e.g. -d: -d,)"),
            ("-f", "field numbers (e.g. -f1,3)"),
            ("-c", "character positions"),
        ],
        "watch" => &[
            ("-n", "interval seconds (e.g. -n 1)"),
            ("-d", "highlight differences"),
        ],
        "tmux" => &[
            ("new -s", "create named session"),
            ("attach -t", "attach to session"),
            ("ls", "list sessions"),
            ("kill-session -t", "kill session"),
        ],
        "ss" => &[
            ("-t", "TCP sockets"),
            ("-u", "UDP sockets"),
            ("-l", "listening sockets"),
            ("-p", "show process"),
            ("-n", "numeric (no DNS)"),
            ("-tulpen", "TCP+UDP listen with process (common)"),
            ("-tunap", "TCP+UDP active with process"),
        ],
        "lsof" => &[
            ("-i", "network connections (e.g. -i :8080)"),
            ("-iTCP", "TCP connections only"),
            ("-sTCP:LISTEN", "only listening TCP"),
            ("-P", "no port name resolution"),
            ("-n", "no DNS resolution"),
        ],
        "ip" => &[
            ("addr", "show IP addresses"),
            ("route", "show routing table"),
            ("link", "show network interfaces"),
        ],
        "ping" => &[
            ("-c", "count (e.g. -c 4)"),
            ("-i", "interval seconds"),
            ("-W", "timeout seconds"),
        ],
        "dig" => &[
            ("+short", "short answer only"),
            ("A", "query A record"),
            ("MX", "query MX record"),
            ("NS", "query nameservers"),
        ],
        "openssl" => &[
            ("version", "show version"),
            ("s_client -connect", "debug TLS connection"),
            ("x509 -text -noout", "inspect certificate"),
            ("rand -hex 32", "generate random hex secret"),
            ("req -newkey rsa:2048", "create key + CSR"),
        ],
        "ufw" => &[
            ("status verbose", "show firewall status"),
            ("allow", "allow port/service"),
            ("deny", "deny port/service"),
            ("delete", "remove rule"),
            ("enable", "enable firewall"),
            ("disable", "disable firewall"),
        ],
        "nginx" => &[
            ("-t", "test config syntax"),
            ("-s reload", "signal reload"),
        ],
        "make" => &[
            ("test", "run test target"),
            ("build", "run build target"),
            ("clean", "run clean target"),
            ("-j4", "parallel jobs (4 cores)"),
            ("-B", "force rebuild all"),
        ],
        "apt" | "apt-get" => &[
            ("update", "refresh package index"),
            ("upgrade", "upgrade packages"),
            ("install", "install package"),
            ("remove", "remove package"),
            ("autoremove", "remove unused deps"),
            ("search", "search packages"),
            ("list --installed", "show installed"),
        ],
        "yum" | "dnf" => &[
            ("install", "install package"),
            ("remove", "remove package"),
            ("update", "update packages"),
            ("search", "search packages"),
            ("list", "list packages"),
            ("info", "show package info"),
            ("clean all", "clean package cache"),
        ],
        "npm" => &[
            ("install", "install packages"),
            ("ci", "clean reproducible install (CI)"),
            ("run", "run script"),
            ("run dev", "run dev script"),
            ("run build", "build project"),
            ("start", "start project"),
            ("test", "run tests"),
            ("outdated", "check outdated deps"),
            ("audit", "security audit"),
            ("-D", "save as devDependency"),
            ("-g", "global install"),
        ],
        "cargo" => &[
            ("build", "compile the project"),
            ("run", "build and run"),
            ("test", "run tests"),
            ("check", "check without building"),
            ("clippy", "run linter"),
            ("fmt", "format code"),
            ("add", "add dependency"),
            ("--release", "release profile"),
        ],
        "pip" | "pip3" => &[
            ("install", "install package"),
            ("install -r", "install from requirements.txt"),
            ("uninstall", "remove package"),
            ("freeze", "output installed packages"),
            ("list", "list installed packages"),
            ("list --outdated", "check outdated"),
            ("show", "show package info"),
            ("--upgrade", "upgrade package"),
        ],
        "python" | "python3" => &[
            ("-m venv", "create virtual environment"),
            ("-m pytest", "run tests"),
            ("-m http.server", "simple local server"),
            ("-m pip install --upgrade pip", "upgrade pip"),
            ("-c", "run inline code"),
        ],
        "psql" => &[
            ("-h", "host"),
            ("-U", "username"),
            ("-d", "database name"),
            ("-c", "run single query"),
            ("-f", "execute SQL file"),
        ],
        "mysql" => &[
            ("-u", "username"),
            ("-p", "prompt password"),
            ("-h", "host"),
            ("-e", "execute statement"),
        ],
        "redis-cli" => &[
            ("ping", "check connectivity"),
            ("info memory", "memory usage info"),
            ("monitor", "watch commands real-time"),
            ("keys", "list matching keys"),
            ("get", "get key value"),
            ("set", "set key value"),
        ],
        "crontab" => &[
            ("-l", "list current cron jobs"),
            ("-e", "edit cron jobs"),
            ("-u", "specify user"),
        ],
        _ => &[],
    }
}
