// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/sftp.dart';
import 'api/ssh.dart';
import 'dart:async';
import 'dart:convert';
import 'domain/profile.dart';
import 'domain/session.dart';
import 'domain/sftp.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSshInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1466402889;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'portix_serv',
        ioDirectory: '../portix_serv/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<SessionInfo> crateApiSshConnect({
    required SshProfile profile,
    required int cols,
    required int rows,
  });

  Stream<String> crateApiSshConnectionStatusStream();

  Future<void> crateApiSshDisconnect({required String sessionId});

  Stream<String> crateApiSshErrorEventStream();

  Future<String> crateApiSshGenerateEd25519Key({
    required String path,
    required String comment,
    String? passphrase,
  });

  Future<void> crateApiSshInitApp();

  Future<List<ForwardInfo>> crateApiSshListLocalForwards();

  Future<HostKeyInfo?> crateApiSshPendingHostKey({
    required String host,
    required int port,
  });

  Future<RemoteSystemSnapshot> crateApiSshRemoteSystemSnapshot({
    required String sessionId,
  });

  Future<void> crateApiSshResizeTerminal({
    required String sessionId,
    required int cols,
    required int rows,
  });

  Future<void> crateApiSshSendTerminalInput({
    required String sessionId,
    required List<int> data,
  });

  Future<void> crateApiSftpSftpChmod({
    required String sessionId,
    required String path,
    required int mode,
  });

  Future<String> crateApiSftpSftpConnect({required SshProfile profile});

  Future<void> crateApiSftpSftpCopy({
    required String sessionId,
    required String from,
    required String to,
  });

  Future<void> crateApiSftpSftpCreateDir({
    required String sessionId,
    required String path,
  });

  Future<void> crateApiSftpSftpCreateFile({
    required String sessionId,
    required String path,
  });

  Future<void> crateApiSftpSftpDisconnect({required String sessionId});

  Stream<TransferProgress> crateApiSftpSftpDownload({
    required String sessionId,
    required String remotePath,
    required String localPath,
  });

  Future<bool> crateApiSftpSftpIsAlive({required String sessionId});

  Future<List<RemoteFileEntry>> crateApiSftpSftpList({
    required String sessionId,
    required String path,
  });

  Future<Uint8List> crateApiSftpSftpRead({
    required String sessionId,
    required String path,
  });

  Future<void> crateApiSftpSftpRemove({
    required String sessionId,
    required String path,
  });

  Future<void> crateApiSftpSftpRename({
    required String sessionId,
    required String from,
    required String to,
  });

  Future<String> crateApiSftpSftpResolve({
    required String sessionId,
    required String path,
  });

  Stream<TransferProgress> crateApiSftpSftpUpload({
    required String sessionId,
    required String localPath,
    required String remotePath,
  });

  Future<void> crateApiSftpSftpWrite({
    required String sessionId,
    required String path,
    required List<int> data,
  });

  Future<ForwardInfo> crateApiSshStartLocalForward({
    required SshProfile profile,
    required int localPort,
    required String remoteHost,
    required int remotePort,
  });

  Future<ForwardInfo> crateApiSshStartRemoteForward({
    required SshProfile profile,
    required int remotePort,
    required String localHost,
    required int localPort,
  });

  Future<ForwardInfo> crateApiSshStartSocksProxy({
    required SshProfile profile,
    required int localPort,
  });

  Future<void> crateApiSshStopLocalForward({required String id});

  Stream<String> crateApiSshTerminalOutputStream();

  Future<void> crateApiSshTrustHostKey({
    required String host,
    required int port,
    required String fingerprint,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<SessionInfo> crateApiSshConnect({
    required SshProfile profile,
    required int cols,
    required int rows,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_ssh_profile(profile, serializer);
          sse_encode_u_32(cols, serializer);
          sse_encode_u_32(rows, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSshConnectConstMeta,
        argValues: [profile, cols, rows],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshConnectConstMeta => const TaskConstMeta(
    debugName: "connect",
    argNames: ["profile", "cols", "rows"],
  );

  @override
  Stream<String> crateApiSshConnectionStatusStream() {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 2,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiSshConnectionStatusStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSshConnectionStatusStreamConstMeta =>
      const TaskConstMeta(
        debugName: "connection_status_stream",
        argNames: ["sink"],
      );

  @override
  Future<void> crateApiSshDisconnect({required String sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSshDisconnectConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshDisconnectConstMeta =>
      const TaskConstMeta(debugName: "disconnect", argNames: ["sessionId"]);

  @override
  Stream<String> crateApiSshErrorEventStream() {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 4,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiSshErrorEventStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSshErrorEventStreamConstMeta =>
      const TaskConstMeta(debugName: "error_event_stream", argNames: ["sink"]);

  @override
  Future<String> crateApiSshGenerateEd25519Key({
    required String path,
    required String comment,
    String? passphrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(comment, serializer);
          sse_encode_opt_String(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSshGenerateEd25519KeyConstMeta,
        argValues: [path, comment, passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshGenerateEd25519KeyConstMeta =>
      const TaskConstMeta(
        debugName: "generate_ed25519_key",
        argNames: ["path", "comment", "passphrase"],
      );

  @override
  Future<void> crateApiSshInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSshInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<ForwardInfo>> crateApiSshListLocalForwards() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_forward_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSshListLocalForwardsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshListLocalForwardsConstMeta =>
      const TaskConstMeta(debugName: "list_local_forwards", argNames: []);

  @override
  Future<HostKeyInfo?> crateApiSshPendingHostKey({
    required String host,
    required int port,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_host_key_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSshPendingHostKeyConstMeta,
        argValues: [host, port],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshPendingHostKeyConstMeta => const TaskConstMeta(
    debugName: "pending_host_key",
    argNames: ["host", "port"],
  );

  @override
  Future<RemoteSystemSnapshot> crateApiSshRemoteSystemSnapshot({
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_remote_system_snapshot,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSshRemoteSystemSnapshotConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshRemoteSystemSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "remote_system_snapshot",
        argNames: ["sessionId"],
      );

  @override
  Future<void> crateApiSshResizeTerminal({
    required String sessionId,
    required int cols,
    required int rows,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_u_32(cols, serializer);
          sse_encode_u_32(rows, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSshResizeTerminalConstMeta,
        argValues: [sessionId, cols, rows],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshResizeTerminalConstMeta => const TaskConstMeta(
    debugName: "resize_terminal",
    argNames: ["sessionId", "cols", "rows"],
  );

  @override
  Future<void> crateApiSshSendTerminalInput({
    required String sessionId,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSshSendTerminalInputConstMeta,
        argValues: [sessionId, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshSendTerminalInputConstMeta =>
      const TaskConstMeta(
        debugName: "send_terminal_input",
        argNames: ["sessionId", "data"],
      );

  @override
  Future<void> crateApiSftpSftpChmod({
    required String sessionId,
    required String path,
    required int mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(path, serializer);
          sse_encode_u_32(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSftpSftpChmodConstMeta,
        argValues: [sessionId, path, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpChmodConstMeta => const TaskConstMeta(
    debugName: "sftp_chmod",
    argNames: ["sessionId", "path", "mode"],
  );

  @override
  Future<String> crateApiSftpSftpConnect({required SshProfile profile}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_ssh_profile(profile, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSftpSftpConnectConstMeta,
        argValues: [profile],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpConnectConstMeta =>
      const TaskConstMeta(debugName: "sftp_connect", argNames: ["profile"]);

  @override
  Future<void> crateApiSftpSftpCopy({
    required String sessionId,
    required String from,
    required String to,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(from, serializer);
          sse_encode_String(to, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSftpSftpCopyConstMeta,
        argValues: [sessionId, from, to],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpCopyConstMeta => const TaskConstMeta(
    debugName: "sftp_copy",
    argNames: ["sessionId", "from", "to"],
  );

  @override
  Future<void> crateApiSftpSftpCreateDir({
    required String sessionId,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSftpSftpCreateDirConstMeta,
        argValues: [sessionId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpCreateDirConstMeta => const TaskConstMeta(
    debugName: "sftp_create_dir",
    argNames: ["sessionId", "path"],
  );

  @override
  Future<void> crateApiSftpSftpCreateFile({
    required String sessionId,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSftpSftpCreateFileConstMeta,
        argValues: [sessionId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpCreateFileConstMeta => const TaskConstMeta(
    debugName: "sftp_create_file",
    argNames: ["sessionId", "path"],
  );

  @override
  Future<void> crateApiSftpSftpDisconnect({required String sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSftpSftpDisconnectConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpDisconnectConstMeta => const TaskConstMeta(
    debugName: "sftp_disconnect",
    argNames: ["sessionId"],
  );

  @override
  Stream<TransferProgress> crateApiSftpSftpDownload({
    required String sessionId,
    required String remotePath,
    required String localPath,
  }) {
    final sink = RustStreamSink<TransferProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(sessionId, serializer);
            sse_encode_String(remotePath, serializer);
            sse_encode_String(localPath, serializer);
            sse_encode_StreamSink_transfer_progress_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 18,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiSftpSftpDownloadConstMeta,
          argValues: [sessionId, remotePath, localPath, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSftpSftpDownloadConstMeta => const TaskConstMeta(
    debugName: "sftp_download",
    argNames: ["sessionId", "remotePath", "localPath", "sink"],
  );

  @override
  Future<bool> crateApiSftpSftpIsAlive({required String sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSftpSftpIsAliveConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpIsAliveConstMeta =>
      const TaskConstMeta(debugName: "sftp_is_alive", argNames: ["sessionId"]);

  @override
  Future<List<RemoteFileEntry>> crateApiSftpSftpList({
    required String sessionId,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_remote_file_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSftpSftpListConstMeta,
        argValues: [sessionId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpListConstMeta => const TaskConstMeta(
    debugName: "sftp_list",
    argNames: ["sessionId", "path"],
  );

  @override
  Future<Uint8List> crateApiSftpSftpRead({
    required String sessionId,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSftpSftpReadConstMeta,
        argValues: [sessionId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpReadConstMeta => const TaskConstMeta(
    debugName: "sftp_read",
    argNames: ["sessionId", "path"],
  );

  @override
  Future<void> crateApiSftpSftpRemove({
    required String sessionId,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSftpSftpRemoveConstMeta,
        argValues: [sessionId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpRemoveConstMeta => const TaskConstMeta(
    debugName: "sftp_remove",
    argNames: ["sessionId", "path"],
  );

  @override
  Future<void> crateApiSftpSftpRename({
    required String sessionId,
    required String from,
    required String to,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(from, serializer);
          sse_encode_String(to, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSftpSftpRenameConstMeta,
        argValues: [sessionId, from, to],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpRenameConstMeta => const TaskConstMeta(
    debugName: "sftp_rename",
    argNames: ["sessionId", "from", "to"],
  );

  @override
  Future<String> crateApiSftpSftpResolve({
    required String sessionId,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSftpSftpResolveConstMeta,
        argValues: [sessionId, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpResolveConstMeta => const TaskConstMeta(
    debugName: "sftp_resolve",
    argNames: ["sessionId", "path"],
  );

  @override
  Stream<TransferProgress> crateApiSftpSftpUpload({
    required String sessionId,
    required String localPath,
    required String remotePath,
  }) {
    final sink = RustStreamSink<TransferProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(sessionId, serializer);
            sse_encode_String(localPath, serializer);
            sse_encode_String(remotePath, serializer);
            sse_encode_StreamSink_transfer_progress_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 25,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiSftpSftpUploadConstMeta,
          argValues: [sessionId, localPath, remotePath, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSftpSftpUploadConstMeta => const TaskConstMeta(
    debugName: "sftp_upload",
    argNames: ["sessionId", "localPath", "remotePath", "sink"],
  );

  @override
  Future<void> crateApiSftpSftpWrite({
    required String sessionId,
    required String path,
    required List<int> data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(path, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSftpSftpWriteConstMeta,
        argValues: [sessionId, path, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpWriteConstMeta => const TaskConstMeta(
    debugName: "sftp_write",
    argNames: ["sessionId", "path", "data"],
  );

  @override
  Future<ForwardInfo> crateApiSshStartLocalForward({
    required SshProfile profile,
    required int localPort,
    required String remoteHost,
    required int remotePort,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_ssh_profile(profile, serializer);
          sse_encode_u_16(localPort, serializer);
          sse_encode_String(remoteHost, serializer);
          sse_encode_u_16(remotePort, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_forward_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSshStartLocalForwardConstMeta,
        argValues: [profile, localPort, remoteHost, remotePort],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshStartLocalForwardConstMeta =>
      const TaskConstMeta(
        debugName: "start_local_forward",
        argNames: ["profile", "localPort", "remoteHost", "remotePort"],
      );

  @override
  Future<ForwardInfo> crateApiSshStartRemoteForward({
    required SshProfile profile,
    required int remotePort,
    required String localHost,
    required int localPort,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_ssh_profile(profile, serializer);
          sse_encode_u_16(remotePort, serializer);
          sse_encode_String(localHost, serializer);
          sse_encode_u_16(localPort, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_forward_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSshStartRemoteForwardConstMeta,
        argValues: [profile, remotePort, localHost, localPort],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshStartRemoteForwardConstMeta =>
      const TaskConstMeta(
        debugName: "start_remote_forward",
        argNames: ["profile", "remotePort", "localHost", "localPort"],
      );

  @override
  Future<ForwardInfo> crateApiSshStartSocksProxy({
    required SshProfile profile,
    required int localPort,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_ssh_profile(profile, serializer);
          sse_encode_u_16(localPort, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_forward_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSshStartSocksProxyConstMeta,
        argValues: [profile, localPort],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshStartSocksProxyConstMeta => const TaskConstMeta(
    debugName: "start_socks_proxy",
    argNames: ["profile", "localPort"],
  );

  @override
  Future<void> crateApiSshStopLocalForward({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSshStopLocalForwardConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshStopLocalForwardConstMeta =>
      const TaskConstMeta(debugName: "stop_local_forward", argNames: ["id"]);

  @override
  Stream<String> crateApiSshTerminalOutputStream() {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 31,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiSshTerminalOutputStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSshTerminalOutputStreamConstMeta =>
      const TaskConstMeta(
        debugName: "terminal_output_stream",
        argNames: ["sink"],
      );

  @override
  Future<void> crateApiSshTrustHostKey({
    required String host,
    required int port,
    required String fingerprint,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_String(fingerprint, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSshTrustHostKeyConstMeta,
        argValues: [host, port, fingerprint],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSshTrustHostKeyConstMeta => const TaskConstMeta(
    debugName: "trust_host_key",
    argNames: ["host", "port", "fingerprint"],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<TransferProgress> dco_decode_StreamSink_transfer_progress_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  HostKeyInfo dco_decode_box_autoadd_host_key_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_host_key_info(raw);
  }

  @protected
  SshProfile dco_decode_box_autoadd_ssh_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ssh_profile(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  SshProfile dco_decode_box_ssh_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ssh_profile(raw);
  }

  @protected
  ConnectionStatus dco_decode_connection_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ConnectionStatus.values[raw as int];
  }

  @protected
  ForwardInfo dco_decode_forward_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ForwardInfo(
      id: dco_decode_String(arr[0]),
      profileId: dco_decode_String(arr[1]),
      localPort: dco_decode_u_16(arr[2]),
      remoteHost: dco_decode_String(arr[3]),
      remotePort: dco_decode_u_16(arr[4]),
      socks: dco_decode_bool(arr[5]),
      reverse: dco_decode_bool(arr[6]),
    );
  }

  @protected
  HostKeyInfo dco_decode_host_key_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return HostKeyInfo(
      algorithm: dco_decode_String(arr[0]),
      fingerprint: dco_decode_String(arr[1]),
      changedLine: dco_decode_opt_box_autoadd_u_32(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<ForwardInfo> dco_decode_list_forward_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_forward_info).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RemoteFileEntry> dco_decode_list_remote_file_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_remote_file_entry).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  HostKeyInfo? dco_decode_opt_box_autoadd_host_key_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_host_key_info(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  SshProfile? dco_decode_opt_box_ssh_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_ssh_profile(raw);
  }

  @protected
  RemoteFileEntry dco_decode_remote_file_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return RemoteFileEntry(
      name: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      isDirectory: dco_decode_bool(arr[2]),
      sizeBytes: dco_decode_u_64(arr[3]),
      modifiedUnixSeconds: dco_decode_i_64(arr[4]),
      mode: dco_decode_u_32(arr[5]),
    );
  }

  @protected
  RemoteSystemSnapshot dco_decode_remote_system_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return RemoteSystemSnapshot(
      os: dco_decode_String(arr[0]),
      hostname: dco_decode_String(arr[1]),
      uptime: dco_decode_String(arr[2]),
      memory: dco_decode_String(arr[3]),
      disk: dco_decode_String(arr[4]),
      memoryUsedBytes: dco_decode_u_64(arr[5]),
      memoryFreeBytes: dco_decode_u_64(arr[6]),
      memoryTotalBytes: dco_decode_u_64(arr[7]),
      diskUsedBytes: dco_decode_u_64(arr[8]),
      diskFreeBytes: dco_decode_u_64(arr[9]),
      diskTotalBytes: dco_decode_u_64(arr[10]),
    );
  }

  @protected
  SessionInfo dco_decode_session_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SessionInfo(
      id: dco_decode_String(arr[0]),
      profileId: dco_decode_String(arr[1]),
      status: dco_decode_connection_status(arr[2]),
    );
  }

  @protected
  SshProfile dco_decode_ssh_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return SshProfile(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      host: dco_decode_String(arr[2]),
      port: dco_decode_u_16(arr[3]),
      username: dco_decode_String(arr[4]),
      password: dco_decode_opt_String(arr[5]),
      privateKeyPath: dco_decode_opt_String(arr[6]),
      keyPassphrase: dco_decode_opt_String(arr[7]),
      jumpHost: dco_decode_opt_box_ssh_profile(arr[8]),
    );
  }

  @protected
  TransferProgress dco_decode_transfer_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TransferProgress(
      done: dco_decode_u_64(arr[0]),
      total: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<TransferProgress> sse_decode_StreamSink_transfer_progress_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  HostKeyInfo sse_decode_box_autoadd_host_key_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_host_key_info(deserializer));
  }

  @protected
  SshProfile sse_decode_box_autoadd_ssh_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ssh_profile(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  SshProfile sse_decode_box_ssh_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ssh_profile(deserializer));
  }

  @protected
  ConnectionStatus sse_decode_connection_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ConnectionStatus.values[inner];
  }

  @protected
  ForwardInfo sse_decode_forward_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_profileId = sse_decode_String(deserializer);
    var var_localPort = sse_decode_u_16(deserializer);
    var var_remoteHost = sse_decode_String(deserializer);
    var var_remotePort = sse_decode_u_16(deserializer);
    var var_socks = sse_decode_bool(deserializer);
    var var_reverse = sse_decode_bool(deserializer);
    return ForwardInfo(
      id: var_id,
      profileId: var_profileId,
      localPort: var_localPort,
      remoteHost: var_remoteHost,
      remotePort: var_remotePort,
      socks: var_socks,
      reverse: var_reverse,
    );
  }

  @protected
  HostKeyInfo sse_decode_host_key_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_algorithm = sse_decode_String(deserializer);
    var var_fingerprint = sse_decode_String(deserializer);
    var var_changedLine = sse_decode_opt_box_autoadd_u_32(deserializer);
    return HostKeyInfo(
      algorithm: var_algorithm,
      fingerprint: var_fingerprint,
      changedLine: var_changedLine,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<ForwardInfo> sse_decode_list_forward_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ForwardInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_forward_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RemoteFileEntry> sse_decode_list_remote_file_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RemoteFileEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_remote_file_entry(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  HostKeyInfo? sse_decode_opt_box_autoadd_host_key_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_host_key_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SshProfile? sse_decode_opt_box_ssh_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_ssh_profile(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RemoteFileEntry sse_decode_remote_file_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_isDirectory = sse_decode_bool(deserializer);
    var var_sizeBytes = sse_decode_u_64(deserializer);
    var var_modifiedUnixSeconds = sse_decode_i_64(deserializer);
    var var_mode = sse_decode_u_32(deserializer);
    return RemoteFileEntry(
      name: var_name,
      path: var_path,
      isDirectory: var_isDirectory,
      sizeBytes: var_sizeBytes,
      modifiedUnixSeconds: var_modifiedUnixSeconds,
      mode: var_mode,
    );
  }

  @protected
  RemoteSystemSnapshot sse_decode_remote_system_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_os = sse_decode_String(deserializer);
    var var_hostname = sse_decode_String(deserializer);
    var var_uptime = sse_decode_String(deserializer);
    var var_memory = sse_decode_String(deserializer);
    var var_disk = sse_decode_String(deserializer);
    var var_memoryUsedBytes = sse_decode_u_64(deserializer);
    var var_memoryFreeBytes = sse_decode_u_64(deserializer);
    var var_memoryTotalBytes = sse_decode_u_64(deserializer);
    var var_diskUsedBytes = sse_decode_u_64(deserializer);
    var var_diskFreeBytes = sse_decode_u_64(deserializer);
    var var_diskTotalBytes = sse_decode_u_64(deserializer);
    return RemoteSystemSnapshot(
      os: var_os,
      hostname: var_hostname,
      uptime: var_uptime,
      memory: var_memory,
      disk: var_disk,
      memoryUsedBytes: var_memoryUsedBytes,
      memoryFreeBytes: var_memoryFreeBytes,
      memoryTotalBytes: var_memoryTotalBytes,
      diskUsedBytes: var_diskUsedBytes,
      diskFreeBytes: var_diskFreeBytes,
      diskTotalBytes: var_diskTotalBytes,
    );
  }

  @protected
  SessionInfo sse_decode_session_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_profileId = sse_decode_String(deserializer);
    var var_status = sse_decode_connection_status(deserializer);
    return SessionInfo(
      id: var_id,
      profileId: var_profileId,
      status: var_status,
    );
  }

  @protected
  SshProfile sse_decode_ssh_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_password = sse_decode_opt_String(deserializer);
    var var_privateKeyPath = sse_decode_opt_String(deserializer);
    var var_keyPassphrase = sse_decode_opt_String(deserializer);
    var var_jumpHost = sse_decode_opt_box_ssh_profile(deserializer);
    return SshProfile(
      id: var_id,
      name: var_name,
      host: var_host,
      port: var_port,
      username: var_username,
      password: var_password,
      privateKeyPath: var_privateKeyPath,
      keyPassphrase: var_keyPassphrase,
      jumpHost: var_jumpHost,
    );
  }

  @protected
  TransferProgress sse_decode_transfer_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_done = sse_decode_u_64(deserializer);
    var var_total = sse_decode_u_64(deserializer);
    return TransferProgress(done: var_done, total: var_total);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_transfer_progress_Sse(
    RustStreamSink<TransferProgress> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_transfer_progress,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_host_key_info(
    HostKeyInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_host_key_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ssh_profile(
    SshProfile self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ssh_profile(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_ssh_profile(SshProfile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ssh_profile(self, serializer);
  }

  @protected
  void sse_encode_connection_status(
    ConnectionStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_forward_info(ForwardInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.profileId, serializer);
    sse_encode_u_16(self.localPort, serializer);
    sse_encode_String(self.remoteHost, serializer);
    sse_encode_u_16(self.remotePort, serializer);
    sse_encode_bool(self.socks, serializer);
    sse_encode_bool(self.reverse, serializer);
  }

  @protected
  void sse_encode_host_key_info(HostKeyInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.algorithm, serializer);
    sse_encode_String(self.fingerprint, serializer);
    sse_encode_opt_box_autoadd_u_32(self.changedLine, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_forward_info(
    List<ForwardInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_forward_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_remote_file_entry(
    List<RemoteFileEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_remote_file_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_host_key_info(
    HostKeyInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_host_key_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_ssh_profile(
    SshProfile? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_ssh_profile(self, serializer);
    }
  }

  @protected
  void sse_encode_remote_file_entry(
    RemoteFileEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_bool(self.isDirectory, serializer);
    sse_encode_u_64(self.sizeBytes, serializer);
    sse_encode_i_64(self.modifiedUnixSeconds, serializer);
    sse_encode_u_32(self.mode, serializer);
  }

  @protected
  void sse_encode_remote_system_snapshot(
    RemoteSystemSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.os, serializer);
    sse_encode_String(self.hostname, serializer);
    sse_encode_String(self.uptime, serializer);
    sse_encode_String(self.memory, serializer);
    sse_encode_String(self.disk, serializer);
    sse_encode_u_64(self.memoryUsedBytes, serializer);
    sse_encode_u_64(self.memoryFreeBytes, serializer);
    sse_encode_u_64(self.memoryTotalBytes, serializer);
    sse_encode_u_64(self.diskUsedBytes, serializer);
    sse_encode_u_64(self.diskFreeBytes, serializer);
    sse_encode_u_64(self.diskTotalBytes, serializer);
  }

  @protected
  void sse_encode_session_info(SessionInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.profileId, serializer);
    sse_encode_connection_status(self.status, serializer);
  }

  @protected
  void sse_encode_ssh_profile(SshProfile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_opt_String(self.password, serializer);
    sse_encode_opt_String(self.privateKeyPath, serializer);
    sse_encode_opt_String(self.keyPassphrase, serializer);
    sse_encode_opt_box_ssh_profile(self.jumpHost, serializer);
  }

  @protected
  void sse_encode_transfer_progress(
    TransferProgress self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.done, serializer);
    sse_encode_u_64(self.total, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
