/// Maps file extensions to categories and suggested openers.
class FileTypeRegistry {
  const FileTypeRegistry._();

  static FileCategory categoryFor(String fileName) {
    final ext = _extension(fileName).toLowerCase();
    if (ext.isEmpty) {
      if (fileName.startsWith('.')) return FileCategory.code;
      return FileCategory.unknown;
    }
    for (final entry in _categoryMap.entries) {
      if (entry.value.contains(ext)) return entry.key;
    }
    return FileCategory.unknown;
  }

  static String labelFor(FileCategory category) {
    return switch (category) {
      FileCategory.document => 'Document',
      FileCategory.image => 'Image',
      FileCategory.audio => 'Audio',
      FileCategory.video => 'Video',
      FileCategory.archive => 'Archive',
      FileCategory.code => 'Code',
      FileCategory.executable => 'Executable',
      FileCategory.database => 'Database',
      FileCategory.design => 'Design',
      FileCategory.unknown => 'File',
    };
  }

  /// Whether this file type should be opened in a code editor by default.
  static bool isCodeFile(String fileName) {
    final cat = categoryFor(fileName);
    return cat == FileCategory.code;
  }

  /// Whether this file type can be previewed as text.
  static bool isTextViewable(String fileName) {
    final cat = categoryFor(fileName);
    return cat == FileCategory.code || cat == FileCategory.document;
  }

  /// Returns the SVG asset path for the file's extension, or `null` if no
  /// matching icon asset exists.
  static String? assetForExtension(String fileName) {
    final ext = _extension(fileName).toLowerCase();
    if (ext.isEmpty) return null;
    return _extensionIconMap[ext];
  }

  static String _extension(String fileName) {
    final index = fileName.lastIndexOf('.');
    if (index < 0 || index == fileName.length - 1) return '';
    return fileName.substring(index + 1);
  }

  static const Map<FileCategory, Set<String>> _categoryMap = {
    FileCategory.document: {
      'txt',
      'doc',
      'docx',
      'pdf',
      'xls',
      'xlsx',
      'ppt',
      'pptx',
      'csv',
      'rtf',
      'odt',
      'ods',
      'odp',
      'md',
      'pages',
      'numbers',
    },
    FileCategory.image: {
      'jpg',
      'jpeg',
      'png',
      'gif',
      'bmp',
      'webp',
      'svg',
      'psd',
      'tiff',
      'tif',
      'ico',
      'heic',
      'heif',
      'raw',
      'cr2',
      'nef',
    },
    FileCategory.audio: {
      'mp3',
      'wav',
      'flac',
      'aac',
      'ogg',
      'wma',
      'm4a',
      'opus',
      'aiff',
    },
    FileCategory.video: {
      'mp4',
      'mkv',
      'avi',
      'mov',
      'wmv',
      'flv',
      'webm',
      'm4v',
      'mpg',
      'mpeg',
    },
    FileCategory.archive: {
      'zip',
      'rar',
      '7z',
      'tar',
      'gz',
      'bz2',
      'xz',
      'zst',
      'lz',
      'tgz',
      'tar.gz',
      'tar.bz2',
      'tar.xz',
      'deb',
      'rpm',
      'dmg',
      'iso',
    },
    FileCategory.code: {
      'py',
      'js',
      'ts',
      'jsx',
      'tsx',
      'html',
      'css',
      'scss',
      'sass',
      'json',
      'xml',
      'yaml',
      'yml',
      'java',
      'cpp',
      'c',
      'h',
      'hpp',
      'cs',
      'go',
      'rs',
      'rb',
      'php',
      'swift',
      'kt',
      'kts',
      'dart',
      'lua',
      'sh',
      'bash',
      'zsh',
      'fish',
      'ps1',
      'bat',
      'cmd',
      'sql',
      'graphql',
      'proto',
      'toml',
      'ini',
      'conf',
      'env',
      'dockerfile',
      'makefile',
      'cmake',
      'gradle',
      'groovy',
      'vue',
      'svelte',
      'astro',
      'elm',
      'ex',
      'exs',
      'erl',
      'hs',
      'ml',
      'mli',
      'clj',
      'cljs',
      'scala',
      'r',
      'jl',
      'nim',
      'zig',
      'tf',
      'hcl',
      'plist',
      'lock',
      'mod',
      'sum',
      'cabal',
    },
    FileCategory.executable: {
      'exe',
      'msi',
      'apk',
      'ipa',
      'app',
      'deb',
      'rpm',
      'bin',
      'run',
      'appimage',
      'snap',
      'flatpak',
    },
    FileCategory.database: {'db', 'sqlite', 'sqlite3', 'mdb', 'accdb', 'realm'},
    FileCategory.design: {
      'ai',
      'cdr',
      'xd',
      'fig',
      'sketch',
      'blend',
      'fbx',
      'obj',
      'stl',
      '3ds',
      'dwg',
      'dxf',
    },
  };

  static const Map<String, String> _extensionIconMap = {
    // ── Code / programming ──────────────────────────
    'py': 'assets/icons/extension/python.svg',
    'pyw': 'assets/icons/extension/python.svg',
    'js': 'assets/icons/extension/js.svg',
    'jsx': 'assets/icons/extension/js.svg',
    'ts': 'assets/icons/extension/js.svg',
    'tsx': 'assets/icons/extension/js.svg',
    'mjs': 'assets/icons/extension/js.svg',
    'cjs': 'assets/icons/extension/js.svg',
    'javascript': 'assets/icons/extension/javascript.svg',
    'html': 'assets/icons/extension/html.svg',
    'htm': 'assets/icons/extension/html.svg',
    'xhtml': 'assets/icons/extension/html.svg',
    'css': 'assets/icons/extension/css.svg',
    'scss': 'assets/icons/extension/css.svg',
    'sass': 'assets/icons/extension/css.svg',
    'less': 'assets/icons/extension/css.svg',
    'json': 'assets/icons/extension/json.svg',
    'xml': 'assets/icons/extension/xml.svg',
    'svg': 'assets/icons/extension/image.svg',
    'xsd': 'assets/icons/extension/xml.svg',
    'xsl': 'assets/icons/extension/xml.svg',
    'xslt': 'assets/icons/extension/xml.svg',
    'go': 'assets/icons/extension/go.svg',
    'rs': 'assets/icons/extension/rust.svg',
    'java': 'assets/icons/extension/java.svg',
    'class': 'assets/icons/extension/class.svg',
    'jar': 'assets/icons/extension/class.svg',
    'cs': 'assets/icons/extension/class.svg',
    'dart': 'assets/icons/extension/dart.svg',
    'pl': 'assets/icons/extension/perl.svg',
    'pm': 'assets/icons/extension/perl.svg',
    'pod': 'assets/icons/extension/perl.svg',
    'sql': 'assets/icons/extension/sql.svg',
    'swift': 'assets/icons/extension/swift.svg',
    'cpp': 'assets/icons/extension/C++.svg',
    'cc': 'assets/icons/extension/C++.svg',
    'cxx': 'assets/icons/extension/C++.svg',
    'c++': 'assets/icons/extension/C++.svg',
    'c': 'assets/icons/extension/C++.svg',
    'h': 'assets/icons/extension/C++.svg',
    'hpp': 'assets/icons/extension/C++.svg',
    'hxx': 'assets/icons/extension/C++.svg',
    'hh': 'assets/icons/extension/C++.svg',
    'sh': 'assets/icons/extension/terminal.svg',
    'bash': 'assets/icons/extension/terminal.svg',
    'zsh': 'assets/icons/extension/terminal.svg',
    'fish': 'assets/icons/extension/terminal.svg',
    'ps1': 'assets/icons/extension/terminal.svg',
    'bat': 'assets/icons/extension/terminal.svg',
    'cmd': 'assets/icons/extension/terminal.svg',
    // ── Config / environment ────────────────────────
    'env': 'assets/icons/extension/env.svg',
    'yaml': 'assets/icons/extension/yaml.svg',
    'yml': 'assets/icons/extension/yaml.svg',
    'ini': 'assets/icons/extension/document-config.svg',
    'toml': 'assets/icons/extension/document-config.svg',
    'conf': 'assets/icons/extension/document-config.svg',
    'cfg': 'assets/icons/extension/document-config.svg',
    'properties': 'assets/icons/extension/document-config.svg',
    'gradle': 'assets/icons/extension/document-config.svg',
    'dockerfile': 'assets/icons/extension/docker.svg',
    'makefile': 'assets/icons/extension/env.svg',
    // ── Markdown / GitHub ───────────────────────────
    'md': 'assets/icons/extension/markdown.svg',
    'markdown': 'assets/icons/extension/markdown.svg',
    'gitignore': 'assets/icons/extension/github.svg',
    'gitattributes': 'assets/icons/extension/github.svg',
    'gitmodules': 'assets/icons/extension/github.svg',
    // ── Documents ───────────────────────────────────
    'doc': 'assets/icons/extension/word.svg',
    'docx': 'assets/icons/extension/word.svg',
    'rtf': 'assets/icons/extension/word.svg',
    'odt': 'assets/icons/extension/word.svg',
    'pages': 'assets/icons/extension/word.svg',
    'xls': 'assets/icons/extension/excel.svg',
    'xlsx': 'assets/icons/extension/excel.svg',
    'csv': 'assets/icons/extension/excel.svg',
    'ods': 'assets/icons/extension/excel.svg',
    'numbers': 'assets/icons/extension/excel.svg',
    'ppt': 'assets/icons/extension/ppt.svg',
    'pptx': 'assets/icons/extension/ppt.svg',
    'odp': 'assets/icons/extension/ppt.svg',
    'pdf': 'assets/icons/extension/pdf.svg',
    // ── Images ──────────────────────────────────────
    'jpg': 'assets/icons/extension/photo.svg',
    'jpeg': 'assets/icons/extension/photo.svg',
    'png': 'assets/icons/extension/photo.svg',
    'gif': 'assets/icons/extension/photo.svg',
    'bmp': 'assets/icons/extension/photo.svg',
    'webp': 'assets/icons/extension/photo.svg',
    'ico': 'assets/icons/extension/photo.svg',
    'heic': 'assets/icons/extension/photo.svg',
    'heif': 'assets/icons/extension/photo.svg',
    'tiff': 'assets/icons/extension/photo.svg',
    'tif': 'assets/icons/extension/photo.svg',
    'psd': 'assets/icons/extension/photo.svg',
    'raw': 'assets/icons/extension/photo.svg',
    'cr2': 'assets/icons/extension/photo.svg',
    'nef': 'assets/icons/extension/photo.svg',
    // ── Audio ───────────────────────────────────────
    'mp3': 'assets/icons/extension/music.svg',
    'wav': 'assets/icons/extension/music.svg',
    'flac': 'assets/icons/extension/music.svg',
    'aac': 'assets/icons/extension/music.svg',
    'ogg': 'assets/icons/extension/music.svg',
    'wma': 'assets/icons/extension/music.svg',
    'm4a': 'assets/icons/extension/music.svg',
    'opus': 'assets/icons/extension/music.svg',
    'aiff': 'assets/icons/extension/music.svg',
    // ── Archives ────────────────────────────────────
    'zip': 'assets/icons/extension/zip.svg',
    'zipx': 'assets/icons/extension/zip.svg',
    'rar': 'assets/icons/extension/rar.svg',
    'rpm': 'assets/icons/extension/rpm.svg',
    // ── Executables ─────────────────────────────────
    'exe': 'assets/icons/extension/exe.svg',
    'msi': 'assets/icons/extension/exe.svg',
  };
}

enum FileCategory {
  document,
  image,
  audio,
  video,
  archive,
  code,
  executable,
  database,
  design,
  unknown,
}
