// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

enum ConnectionStatus { disconnected, connecting, connected, error }

class RemoteFileEntry {
  final String name;
  final String path;
  final bool isDirectory;
  final BigInt sizeBytes;
  final PlatformInt64 modifiedUnixSeconds;

  const RemoteFileEntry({
    required this.name,
    required this.path,
    required this.isDirectory,
    required this.sizeBytes,
    required this.modifiedUnixSeconds,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      isDirectory.hashCode ^
      sizeBytes.hashCode ^
      modifiedUnixSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteFileEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          isDirectory == other.isDirectory &&
          sizeBytes == other.sizeBytes &&
          modifiedUnixSeconds == other.modifiedUnixSeconds;
}

class RemoteSystemSnapshot {
  final String os;
  final String hostname;
  final String uptime;
  final String memory;
  final String disk;
  final BigInt memoryUsedBytes;
  final BigInt memoryFreeBytes;
  final BigInt memoryTotalBytes;
  final BigInt diskUsedBytes;
  final BigInt diskFreeBytes;
  final BigInt diskTotalBytes;

  const RemoteSystemSnapshot({
    required this.os,
    required this.hostname,
    required this.uptime,
    required this.memory,
    required this.disk,
    required this.memoryUsedBytes,
    required this.memoryFreeBytes,
    required this.memoryTotalBytes,
    required this.diskUsedBytes,
    required this.diskFreeBytes,
    required this.diskTotalBytes,
  });

  @override
  int get hashCode =>
      os.hashCode ^
      hostname.hashCode ^
      uptime.hashCode ^
      memory.hashCode ^
      disk.hashCode ^
      memoryUsedBytes.hashCode ^
      memoryFreeBytes.hashCode ^
      memoryTotalBytes.hashCode ^
      diskUsedBytes.hashCode ^
      diskFreeBytes.hashCode ^
      diskTotalBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteSystemSnapshot &&
          runtimeType == other.runtimeType &&
          os == other.os &&
          hostname == other.hostname &&
          uptime == other.uptime &&
          memory == other.memory &&
          disk == other.disk &&
          memoryUsedBytes == other.memoryUsedBytes &&
          memoryFreeBytes == other.memoryFreeBytes &&
          memoryTotalBytes == other.memoryTotalBytes &&
          diskUsedBytes == other.diskUsedBytes &&
          diskFreeBytes == other.diskFreeBytes &&
          diskTotalBytes == other.diskTotalBytes;
}

class SessionInfo {
  final String id;
  final String profileId;
  final ConnectionStatus status;

  const SessionInfo({
    required this.id,
    required this.profileId,
    required this.status,
  });

  @override
  int get hashCode => id.hashCode ^ profileId.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          profileId == other.profileId &&
          status == other.status;
}
