// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class RemoteFileEntry {
  final String name;
  final String path;
  final bool isDirectory;
  final BigInt sizeBytes;
  final PlatformInt64 modifiedUnixSeconds;

  /// Permission bits (e.g. 0o755); 0 when the server did not report them.
  final int mode;

  const RemoteFileEntry({
    required this.name,
    required this.path,
    required this.isDirectory,
    required this.sizeBytes,
    required this.modifiedUnixSeconds,
    required this.mode,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      isDirectory.hashCode ^
      sizeBytes.hashCode ^
      modifiedUnixSeconds.hashCode ^
      mode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteFileEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          isDirectory == other.isDirectory &&
          sizeBytes == other.sizeBytes &&
          modifiedUnixSeconds == other.modifiedUnixSeconds &&
          mode == other.mode;
}

/// Bytes moved so far out of `total`; a resumed transfer starts above 0.
class TransferProgress {
  final BigInt done;
  final BigInt total;

  const TransferProgress({required this.done, required this.total});

  @override
  int get hashCode => done.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferProgress &&
          runtimeType == other.runtimeType &&
          done == other.done &&
          total == other.total;
}
